### ISSUE TITLE
Server error in auth chain misinterpreted as invalid auth

### ISSUE THREAD

**Issue by ScottNortonPhD** [EGA-archive/ega-download-client#103]
**Description of the bug**

When an error occurs during authentication and the response is malformed, the resulting exception is interpreted as the auth parameters being invalid, with no retry.

**Used versions** (please complete the following information)
 - Operating System version: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Red Hat 4.8.5-44
 - Python version: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;3.8.6
 - PyEGA3 version: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; EGA python client version 3.4.1
     - Please, **confirm you have tested your PyEGA3 installation** (follow [instructions](https://github.com/EGA-archive/ega-download-client#testing-pyega3-installation#Testing-pyEGA3-installation)): Yes

Before creating a bug report, you may want to check if your issue is displayed in the [Troubleshooting](https://github.com/EGA-archive/ega-download-client#Troubleshooting). If the version of PyEGA3 you are using is not the most recent one, we strongly recommend updating PyEGA3 (follow instructions at [Installation and update](https://github.com/EGA-archive/ega-download-client#Installation-and-update)) and checking if the bug still appears.

**To Reproduce**

`pyega3 -c 24 -cf ~/.pyega3.json fetch EGAD00001004363`

**Observed behaviour**

Credentials are checked for each individual file in the dataset. If an auth check fails due to a server error, the program exits on the JSON decode attempt. This is rare and has happened twice within the first 490 files.

**Expected behaviour**

On a temporary authentication failure (5XX status), the program should retry.

**Screenshots and error messages**

```
[2021-01-22 14:03:03 -0500] Invalid username, password or secret key - please check and retry. If problem persists contact helpdesk on helpdesk@ega-archive.org
Traceback (most recent call last):
  File "/home/ssn33/.local/lib/python3.8/site-packages/pyega3/pyega3.py", line 144, in get_token
    reply = r.json()
  File "/home/ssn33/.local/lib/python3.8/site-packages/requests/models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/ssn33/.local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/home/ssn33/.local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/ssn33/.local/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by malloryfreeberg** [comment]
Hi @ScottNortonPhD - Thank you for raising this issue. We briefly discussed internally and agree that the behavior you expect would be the optimal behavior. We are adding this feature to our backlog. Really appreciate you raising this so we can make pyega3 better!
