### ISSUE TITLE
Unable to connect to server?

### ISSUE THREAD

**Issue by alhafidzhamdan** [EGA-archive/ega-download-client#104]
Hi there, 

Is your server down?
A

```
(pyega3) [mhamdan@node2f24(eddie) params]$ pyega3 -d -t fetch EGAF00001775036
[2021-02-06 10:10:35 +0000] 
[2021-02-06 10:10:35 +0000] pyEGA3 - EGA python client version 3.4.1 (https://github.com/EGA-archive/ega-download-client)
[2021-02-06 10:10:35 +0000] Parts of this software are derived from pyEGA (https://github.com/blachlylab/pyega) by James Blachly
[2021-02-06 10:10:35 +0000] Python version : 3.5.5
[2021-02-06 10:10:35 +0000] OS version : Linux #1 SMP Tue Sep 25 14:32:52 CDT 2018
[2021-02-06 10:10:35 +0000] Server URL: https://ega.ebi.ac.uk:8052/elixir/data
[2021-02-06 10:10:35 +0000] Session-Id: 1748839237
[2021-02-06 10:10:35 +0000] Starting new HTTPS connection (1): ega.ebi.ac.uk
[2021-02-06 10:10:37 +0000] https://ega.ebi.ac.uk:8443 "POST /ega-openid-connect-server/token HTTP/1.1" 200 None
[2021-02-06 10:10:37 +0000] 
[2021-02-06 10:10:37 +0000] Authentication success for user 'ega-test-data@ebi.ac.uk'
[2021-02-06 10:10:37 +0000] Starting new HTTPS connection (1): ega.ebi.ac.uk
[2021-02-06 10:10:39 +0000] https://ega.ebi.ac.uk:8052 "GET /elixir/data/metadata/files/EGAF00001775036 HTTP/1.1" 200 None
[2021-02-06 10:10:39 +0000] Request URL : https://ega.ebi.ac.uk:8052/elixir/data/metadata/files/EGAF00001775036
[2021-02-06 10:10:39 +0000] Response    :
 {
    "displayFileName": "ENCFF284YOU.bam.bai",
    "fileSize": 4804928,
    "fileId": "EGAF00001775036",
    "unencryptedChecksum": "3b89b96387db5199fef6ba613f70e27c",
    "datasetId": "EGAD00001003338",
    "fileStatus": "available",
    "unencryptedChecksumType": "MD5",
    "fileName": "EGAZ00001314787/ENCFF284YOU.bam.bai.cip",
    "displayFilePath": "EGAZ00001314787"
}
[2021-02-06 10:10:39 +0000] Starting new HTTPS connection (1): ega.ebi.ac.uk
[2021-02-06 10:10:41 +0000] https://ega.ebi.ac.uk:8443 "POST /ega-openid-connect-server/token HTTP/1.1" 200 None
[2021-02-06 10:10:41 +0000] 
[2021-02-06 10:10:41 +0000] Authentication success for user 'ega-test-data@ebi.ac.uk'
[2021-02-06 10:10:41 +0000] File Id: 'EGAF00001775036'(4804928 bytes).
[2021-02-06 10:10:41 +0000] Output file:'/gpfs/igmmfs01/eddie/Glioblastoma-WGS/WGS/params/EGAF00001775036/ENCFF284YOU.bam.bai'
[2021-02-06 10:10:41 +0000] Total space : 236544.00 GiB
[2021-02-06 10:10:41 +0000] Used space : 170874.31 GiB
[2021-02-06 10:10:41 +0000] Free space : 65669.69 GiB
[2021-02-06 10:10:41 +0000] Download starting [using 1 connection(s)]...
  0%|                                                                                                                           | 0.00/4.80M [00:00<?, ?B/s][2021-02-06 10:10:43 +0000] Starting new HTTPS connection (1): ega.ebi.ac.uk
[2021-02-06 10:11:11 +0000] https://ega.ebi.ac.uk:8052 "GET /elixir/data/files/EGAF00001775036?destinationFormat=plain HTTP/1.1" 206 4804912
  0%|                                                                                                                           | 0.00/4.80M [00:28<?, ?B/s]
[2021-02-06 10:11:11 +0000] __exit__
Traceback (most recent call last):
  File "/exports/igmm/eddie/Glioblastoma-WGS/anaconda/envs/pyega3/lib/python3.5/site-packages/pyega3/pyega3.py", line 494, in download_file_retry
    download_file(token, file_id, file_size, check_sum, num_connections, key, output_file)
  File "/exports/igmm/eddie/Glioblastoma-WGS/anaconda/envs/pyega3/lib/python3.5/site-packages/pyega3/pyega3.py", line 422, in download_file
    for part_file_name in executor.map(download_file_slice_, params):
  File "/exports/igmm/eddie/Glioblastoma-WGS/anaconda/envs/pyega3/lib/python3.5/concurrent/futures/_base.py", line 556, in result_iterator
    yield future.result()
  File "/exports/igmm/eddie/Glioblastoma-WGS/anaconda/envs/pyega3/lib/python3.5/concurrent/futures/_base.py", line 405, in result
    return self.__get_result()
  File "/exports/igmm/eddie/Glioblastoma-WGS/anaconda/envs/pyega3/lib/python3.5/concurrent/futures/_base.py", line 357, in __get_result
    raise self._exception
  File "/exports/igmm/eddie/Glioblastoma-WGS/anaconda/envs/pyega3/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/exports/igmm/eddie/Glioblastoma-WGS/anaconda/envs/pyega3/lib/python3.5/site-packages/pyega3/pyega3.py", line 296, in download_file_slice_
    return download_file_slice(*args)
  File "/exports/igmm/eddie/Glioblastoma-WGS/anaconda/envs/pyega3/lib/python3.5/site-packages/pyega3/pyega3.py", line 280, in download_file_slice
    with requests.get(url, headers=headers, stream=True) as r:
AttributeError: __exit__
[2021-02-06 10:12:12 +0000] retry attempt 1
[2021-02-06 10:12:12 +0000] Download starting [using 1 connection(s)]...
  0%|                                                                                                                           | 0.00/4.80M [00:00<?, ?B/s][2021-02-06 10:12:12 +0000] Starting new HTTPS connection (1): ega.ebi.ac.uk
[2021-02-06 10:12:24 +0000] https://ega.ebi.ac.uk:8052 "GET /elixir/data/files/EGAF00001775036?destinationFormat=plain HTTP/1.1" 206 4804912
  0%|                                                                                                                           | 0.00/4.80M [00:12<?, ?B/s]
[2021-02-06 10:12:24 +0000] __exit__
Traceback (most recent call last):
  File "/exports/igmm/eddie/Glioblastoma-WGS/anaconda/envs/pyega3/lib/python3.5/site-packages/pyega3/pyega3.py", line 494, in download_file_retry
    download_file(token, file_id, file_size, check_sum, num_connections, key, output_file)
  File "/exports/igmm/eddie/Glioblastoma-WGS/anaconda/envs/pyega3/lib/python3.5/site-packages/pyega3/pyega3.py", line 422, in download_file
    for part_file_name in executor.map(download_file_slice_, params):
  File "/exports/igmm/eddie/Glioblastoma-WGS/anaconda/envs/pyega3/lib/python3.5/concurrent/futures/_base.py", line 556, in result_iterator
    yield future.result()
  File "/exports/igmm/eddie/Glioblastoma-WGS/anaconda/envs/pyega3/lib/python3.5/concurrent/futures/_base.py", line 405, in result
    return self.__get_result()
  File "/exports/igmm/eddie/Glioblastoma-WGS/anaconda/envs/pyega3/lib/python3.5/concurrent/futures/_base.py", line 357, in __get_result
    raise self._exception
  File "/exports/igmm/eddie/Glioblastoma-WGS/anaconda/envs/pyega3/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/exports/igmm/eddie/Glioblastoma-WGS/anaconda/envs/pyega3/lib/python3.5/site-packages/pyega3/pyega3.py", line 296, in download_file_slice_
    return download_file_slice(*args)
  File "/exports/igmm/eddie/Glioblastoma-WGS/anaconda/envs/pyega3/lib/python3.5/site-packages/pyega3/pyega3.py", line 280, in download_file_slice
    with requests.get(url, headers=headers, stream=True) as r:
AttributeError: __exit__


```

**Comment by malloryfreeberg** [comment]
Hi @alhafidzhamdan. Thank you for reporting this issue. There was a disruption last week, but this should be resolved now. If you are still experiencing this behavior, please email the EGA Helpdesk at helpdesk@ega-archive.org with this issue and attach the output log produced by pyega3 (pyega3_output.log). The Helpdesk team can then provide further assistance. Thank you!
