### ISSUE TITLE
HTTPError: 500 Server Error

### ISSUE THREAD

**Issue by chenchiaying** [EGA-archive/ega-download-client#105]
**Error with ` pyega3 -t files EGAD00001003338`** 

[2021-03-25 17:01:57 +0800] 
[2021-03-25 17:01:57 +0800] pyEGA3 - EGA python client version 3.4.1 (https://github.com/EGA-archive/ega-download-client)
[2021-03-25 17:01:57 +0800] Parts of this software are derived from pyEGA (https://github.com/blachlylab/pyega) by James Blachly
[2021-03-25 17:01:57 +0800] Python version : 3.8.5
[2021-03-25 17:01:57 +0800] OS version : Linux #50~20.04.1-Ubuntu SMP Wed Feb 10 21:07:30 UTC 2021
[2021-03-25 17:01:57 +0800] Server URL: https://ega.ebi.ac.uk:8052/elixir/data
[2021-03-25 17:01:57 +0800] Session-Id: 1031964486
[2021-03-25 17:02:01 +0800] 
[2021-03-25 17:02:01 +0800] Authentication success for user 'ega-test-data@ebi.ac.uk'
Traceback (most recent call last):
  File "/usr/local/bin/pyega3", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/pyega3/pyega3.py", line 655, in main
    reply = api_list_files_in_dataset(token, args.identifier)
  File "/usr/local/lib/python3.8/dist-packages/pyega3/pyega3.py", line 192, in api_list_files_in_dataset
    if (not dataset in api_list_authorized_datasets(token)):
  File "/usr/local/lib/python3.8/dist-packages/pyega3/pyega3.py", line 163, in api_list_authorized_datasets
    r.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error:  for url: https://ega.ebi.ac.uk:8052/elixir/data/metadata/datasets

**Comment by jesuspc** [comment]
I am also getting an error on this endpoint after authorising a user, but in my case it returns 401:

```
$ pyega3 -d -cf credentials.json datasets

[2021-04-04 13:00:19 +0000]
[2021-04-04 13:00:19 +0000] pyEGA3 - EGA python client version 3.4.1 (https://github.com/EGA-archive/ega-download-client)
[2021-04-04 13:00:19 +0000] Parts of this software are derived from pyEGA (https://github.com/blachlylab/pyega) by James Blachly
[2021-04-04 13:00:19 +0000] Python version : 3.8.5
[2021-04-04 13:00:19 +0000] OS version : Linux #1-NixOS SMP Sun Feb 7 14:35:50 UTC 2021
[2021-04-04 13:00:19 +0000] Server URL: https://ega.ebi.ac.uk:8052/elixir/data
[2021-04-04 13:00:19 +0000] Session-Id: 3554324980
[2021-04-04 13:00:19 +0000] Starting new HTTPS connection (1): ega.ebi.ac.uk:8443
[2021-04-04 13:00:22 +0000] https://ega.ebi.ac.uk:8443 "POST /ega-openid-connect-server/token HTTP/1.1" 200 None
[2021-04-04 13:00:22 +0000]
[2021-04-04 13:00:22 +0000] Authentication success for user '*******'
[2021-04-04 13:00:22 +0000] Starting new HTTPS connection (1): ega.ebi.ac.uk:8052
[2021-04-04 13:01:31 +0000] https://ega.ebi.ac.uk:8052 "GET /elixir/data/metadata/datasets HTTP/1.1" 401 None
Traceback (most recent call last):
  File "/home/jesuspc/Code/projects/pything/env/bin/pyega3", line 8, in <module>
    sys.exit(main())
  File "/home/jesuspc/Code/projects/pything/env/lib/python3.8/site-packages/pyega3/pyega3.py", line 647, in main
    reply = api_list_authorized_datasets(token)
  File "/home/jesuspc/Code/projects/pything/env/lib/python3.8/site-packages/pyega3/pyega3.py", line 163, in api_list_authorized_datasets
    r.raise_for_status()
  File "/nix/store/i814xzc33g05fhf4hdx90ibbi81pwgn7-python3.8-requests-2.24.0/lib/python3.8/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error:  for url: https://ega.ebi.ac.uk:8052/elixir/data/metadata/datasets
```

I've reproduced it by running directly from the provided docker image and via local installation from pip.

**Comment by chenchiaying** [comment]
> **Error with ` pyega3 -t files EGAD00001003338`**
> 
> [2021-03-25 17:01:57 +0800]
> [2021-03-25 17:01:57 +0800] pyEGA3 - EGA python client version 3.4.1 (https://github.com/EGA-archive/ega-download-client)
> [2021-03-25 17:01:57 +0800] Parts of this software are derived from pyEGA (https://github.com/blachlylab/pyega) by James Blachly
> [2021-03-25 17:01:57 +0800] Python version : 3.8.5
> [2021-03-25 17:01:57 +0800] OS version : Linux #50~20.04.1-Ubuntu SMP Wed Feb 10 21:07:30 UTC 2021
> [2021-03-25 17:01:57 +0800] Server URL: https://ega.ebi.ac.uk:8052/elixir/data
> [2021-03-25 17:01:57 +0800] Session-Id: 1031964486
> [2021-03-25 17:02:01 +0800]
> [2021-03-25 17:02:01 +0800] Authentication success for user '[ega-test-data@ebi.ac.uk](mailto:ega-test-data@ebi.ac.uk)'
> Traceback (most recent call last):
> File "/usr/local/bin/pyega3", line 8, in
> sys.exit(main())
> File "/usr/local/lib/python3.8/dist-packages/pyega3/pyega3.py", line 655, in main
> reply = api_list_files_in_dataset(token, args.identifier)
> File "/usr/local/lib/python3.8/dist-packages/pyega3/pyega3.py", line 192, in api_list_files_in_dataset
> if (not dataset in api_list_authorized_datasets(token)):
> File "/usr/local/lib/python3.8/dist-packages/pyega3/pyega3.py", line 163, in api_list_authorized_datasets
> r.raise_for_status()
> File "/usr/lib/python3/dist-packages/requests/models.py", line 940, in raise_for_status
> raise HTTPError(http_error_msg, response=self)
> requests.exceptions.HTTPError: 500 Server Error: for url: https://ega.ebi.ac.uk:8052/elixir/data/metadata/datasets

**Comment by chenchiaying** [comment]
"HTTPError: 500 Server Error"  is something wrong with the EBI server. I tried to download it the next day, and it downloaded normally.

**Comment by malloryfreeberg** [comment]
Hi @chenchiaying - Thank you for reporting this issue. I suspect the 500 error you encountered was due to a temporary disruption in one of our services. If you are still experiencing this behavior (or experience it in the future) please email EGA Helpdesk at helpdesk@ega-archive.org and attach the output log produced by pyega3 (pyega3_output.log). The Helpdesk team can then provide further assistance. Thank you for using pyega3!
