### ISSUE TITLE
401 error on /elixir/data/metadata/datasets with authenticated user

### ISSUE THREAD

**Issue by jesuspc** [EGA-archive/ega-download-client#107]
I am getting a 401 error on the /elixir/data/metadata/datasets endpoint after successfully authorising a user:

```
$ pyega3 -d -cf credentials.json datasets

[2021-04-04 13:00:19 +0000]
[2021-04-04 13:00:19 +0000] pyEGA3 - EGA python client version 3.4.1 (https://github.com/EGA-archive/ega-download-client)
[2021-04-04 13:00:19 +0000] Parts of this software are derived from pyEGA (https://github.com/blachlylab/pyega) by James Blachly
[2021-04-04 13:00:19 +0000] Python version : 3.8.5
[2021-04-04 13:00:19 +0000] OS version : Linux #1-NixOS SMP Sun Feb 7 14:35:50 UTC 2021
[2021-04-04 13:00:19 +0000] Server URL: https://ega.ebi.ac.uk:8052/elixir/data
[2021-04-04 13:00:19 +0000] Session-Id: 3554324980
[2021-04-04 13:00:19 +0000] Starting new HTTPS connection (1): ega.ebi.ac.uk:8443
[2021-04-04 13:00:22 +0000] https://ega.ebi.ac.uk:8443 "POST /ega-openid-connect-server/token HTTP/1.1" 200 None
[2021-04-04 13:00:22 +0000]
[2021-04-04 13:00:22 +0000] Authentication success for user '*******'
[2021-04-04 13:00:22 +0000] Starting new HTTPS connection (1): ega.ebi.ac.uk:8052
[2021-04-04 13:01:31 +0000] https://ega.ebi.ac.uk:8052 "GET /elixir/data/metadata/datasets HTTP/1.1" 401 None
Traceback (most recent call last):
  File "/home/jesuspc/Code/projects/pything/env/bin/pyega3", line 8, in <module>
    sys.exit(main())
  File "/home/jesuspc/Code/projects/pything/env/lib/python3.8/site-packages/pyega3/pyega3.py", line 647, in main
    reply = api_list_authorized_datasets(token)
  File "/home/jesuspc/Code/projects/pything/env/lib/python3.8/site-packages/pyega3/pyega3.py", line 163, in api_list_authorized_datasets
    r.raise_for_status()
  File "/nix/store/i814xzc33g05fhf4hdx90ibbi81pwgn7-python3.8-requests-2.24.0/lib/python3.8/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error:  for url: https://ega.ebi.ac.uk:8052/elixir/data/metadata/datasets
```

I've reproduced it by running directly from the provided docker image and via local installation from pip.

**Comment by anandmohan777** [comment]
@jesuspc We are looking into the issue. Could you provide your username?

**Comment by danarte** [comment]
Hi,
I also got 401 error when trying to fetch a file (a file that I previously fetched with the same client and credentials)
Here is the error:

```
pyega3 -c 24 -cf EGA_credentials.json fetch EGAF00003624515
[2021-04-10 15:16:54 +0300]
[2021-04-10 15:16:54 +0300] pyEGA3 - EGA python client version 3.4.0 (https://github.com/EGA-archive/ega-download-client)
[2021-04-10 15:16:54 +0300] Parts of this software are derived from pyEGA (https://github.com/blachlylab/pyega) by James Blachly
[2021-04-10 15:16:54 +0300] Python version : 3.5.1
[2021-04-10 15:16:54 +0300] OS version : Linux #1 SMP Wed Oct 26 06:52:09 UTC 2016
[2021-04-10 15:16:54 +0300] Server URL: https://ega.ebi.ac.uk:8052/elixir/data
[2021-04-10 15:16:54 +0300] Session-Id: 3805663693
[2021-04-10 15:16:58 +0300]
[2021-04-10 15:16:58 +0300] Authentication success for user 'artemd@mail.tau.ac.il'
Traceback (most recent call last):
  File "/artemd/.local/bin/pyega3", line 8, in <module>
    sys.exit(main())
  File "/artemd/.local/lib/python3.5/site-packages/pyega3/pyega3.py", line 670, in main
    display_file_name, file_name, file_size, check_sum = get_file_name_size_md5(token, args.identifier)
  File "/artemd/.local/lib/python3.5/site-packages/pyega3/pyega3.py", line 250, in get_file_name_size_md5
    r.raise_for_status()
  File "/share/apps/python/python351/lib/python3.5/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error:  for url: https://ega.ebi.ac.uk:8052/elixir/data/metadata/files/EGAF00003624515
```

Hope this helps you resolve the issue soon.
Thanks.

**Comment by anandmohan777** [comment]
Hi @jesuspc and @danarte, 
Thank you for reporting this issue. We have resolved it, if you are still experiencing this behaviour, please email the EGA Helpdesk at helpdesk@ega-archive.org for further assistance.

**Comment by jesuspc** [comment]
Hi @anandmohan777,

I can confirm it works now. Thank you very much for your support and quick response!

**Comment by jianguozhouzunyimedicaluniversity** [comment]
````
There was a problem communicating with the EGA repository: 404 Client Error:  for url: https://ega.ebi.ac.uk:8052/elixir/data/metadata/files/EGAF00004851162%0D
````
Hey, I have the same problem.
