### ISSUE TITLE
500 Server Error:  for url: https://ega.ebi.ac.uk:8052/elixir/data/metadata/datasets

### ISSUE THREAD

**Issue by mdeloger** [EGA-archive/ega-download-client#110]
Hi,

as described in https://github.com/EGA-archive/ega-download-client/issues/52, I get the HTTPError 500 when I try to view my datasets : 

500 Server Error:  for url: https://ega.ebi.ac.uk:8052/elixir/data/metadata/datasets

So I did the update as adviced : 

pip3 install update pyega3 -U
Collecting update
  Downloading update-0.0.1-py2.py3-none-any.whl (2.9 kB)
Requirement already satisfied: pyega3 in /mnt/beegfs/userdata/m_deloger/Conda/Miniconda3-py38_4.8.3/envs/pyega3/lib/python3.9/site-packages (3.4.1)
Requirement already satisfied: requests in /mnt/beegfs/userdata/m_deloger/Conda/Miniconda3-py38_4.8.3/envs/pyega3/lib/python3.9/site-packages (from pyega3) (2.25.1)
Requirement already satisfied: psutil in /mnt/beegfs/userdata/m_deloger/Conda/Miniconda3-py38_4.8.3/envs/pyega3/lib/python3.9/site-packages (from pyega3) (5.8.0)
Requirement already satisfied: tqdm in /mnt/beegfs/userdata/m_deloger/Conda/Miniconda3-py38_4.8.3/envs/pyega3/lib/python3.9/site-packages (from pyega3) (4.59.0)
Requirement already satisfied: htsget in /mnt/beegfs/userdata/m_deloger/Conda/Miniconda3-py38_4.8.3/envs/pyega3/lib/python3.9/site-packages (from pyega3) (0.2.5)
Collecting style==1.1.0
  Downloading style-1.1.0-py2.py3-none-any.whl (6.4 kB)
Requirement already satisfied: idna<3,>=2.5 in /mnt/beegfs/userdata/m_deloger/Conda/Miniconda3-py38_4.8.3/envs/pyega3/lib/python3.9/site-packages (from requests->pyega3) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in /mnt/beegfs/userdata/m_deloger/Conda/Miniconda3-py38_4.8.3/envs/pyega3/lib/python3.9/site-packages (from requests->pyega3) (2020.12.5)
Requirement already satisfied: chardet<5,>=3.0.2 in /mnt/beegfs/userdata/m_deloger/Conda/Miniconda3-py38_4.8.3/envs/pyega3/lib/python3.9/site-packages (from requests->pyega3) (4.0.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /mnt/beegfs/userdata/m_deloger/Conda/Miniconda3-py38_4.8.3/envs/pyega3/lib/python3.9/site-packages (from requests->pyega3) (1.26.4)
Installing collected packages: style, update
Successfully installed style-1.1.0 update-0.0.1

But I still obtain the same error : 

[2021-04-28 08:22:41 +0200]
[2021-04-28 08:22:41 +0200] pyEGA3 - EGA python client version 3.4.1 (https://github.com/EGA-archive/ega-download-client)
[2021-04-28 08:22:41 +0200] Parts of this software are derived from pyEGA (https://github.com/blachlylab/pyega) by James Blachly
[2021-04-28 08:22:41 +0200] Python version : 3.9.4
[2021-04-28 08:22:41 +0200] OS version : Linux #1 SMP Thu Nov 8 23:39:32 UTC 2018
[2021-04-28 08:22:41 +0200] Server URL: https://ega.ebi.ac.uk:8052/elixir/data
[2021-04-28 08:22:41 +0200] Session-Id: 1747291033
[2021-04-28 08:22:44 +0200]
[2021-04-28 08:22:44 +0200] Authentication success for user 'Audrey.Onfroy@inserm.fr'
Traceback (most recent call last):
  File "/mnt/beegfs/userdata/m_deloger/Conda/Miniconda3-py38_4.8.3/envs/pyega3/bin/pyega3", line 10, in <module>
    sys.exit(main())
  File "/mnt/beegfs/userdata/m_deloger/Conda/Miniconda3-py38_4.8.3/envs/pyega3/lib/python3.9/site-packages/pyega3/pyega3.py", line 647, in main
    reply = api_list_authorized_datasets(token)
  File "/mnt/beegfs/userdata/m_deloger/Conda/Miniconda3-py38_4.8.3/envs/pyega3/lib/python3.9/site-packages/pyega3/pyega3.py", line 163, in api_list_authorized_datasets
    r.raise_for_status()
  File "/mnt/beegfs/userdata/m_deloger/Conda/Miniconda3-py38_4.8.3/envs/pyega3/lib/python3.9/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error:  for url: https://ega.ebi.ac.uk:8052/elixir/data/metadata/datasets

May I have your help, please ?

Thank you in advance

**Comment by nwieder** [comment]
I experience the same problem trying to fetch a dataset:

```
CF = "path_to_cred_file.json"
line = EGAF00001381927

pyega3 -c 10 -cf $CF fetch $line --saveto /$line

EGAF00001381927
[2021-04-28 06:46:26 +0000]
[2021-04-28 06:46:26 +0000] pyEGA3 - EGA python client version 3.4.1 (https://github.com/EGA-archive/ega-download-client)
[2021-04-28 06:46:26 +0000] Parts of this software are derived from pyEGA (https://github.com/blachlylab/pyega) by James Blachly
[2021-04-28 06:46:26 +0000] Python version : 3.9.2
[2021-04-28 06:46:26 +0000] OS version : Linux #1 SMP Debian 4.9.65-3+deb9u2 (2018-01-04)
[2021-04-28 06:46:26 +0000] Server URL: https://ega.ebi.ac.uk:8052/elixir/data
[2021-04-28 06:46:26 +0000] Session-Id: 39933991
[2021-04-28 06:46:30 +0000]
[2021-04-28 06:46:30 +0000] Authentication success for user 'nwieder@broadinstitute.org'
Traceback (most recent call last):
  File "/home/nwieder/miniconda3/envs/ega/bin/pyega3", line 10, in <module>
    sys.exit(main())
  File "/home/nwieder/miniconda3/envs/ega/lib/python3.9/site-packages/pyega3/pyega3.py", line 670, in main
    display_file_name, file_name, file_size, check_sum = get_file_name_size_md5(token, args.identifier)
  File "/home/nwieder/miniconda3/envs/ega/lib/python3.9/site-packages/pyega3/pyega3.py", line 250, in get_file_name_size_md5
    r.raise_for_status()
  File "/home/nwieder/miniconda3/envs/ega/lib/python3.9/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error:  for url: https://ega.ebi.ac.uk:8052/elixir/data/metadata/files/EGAF00001381927
```

**Comment by jovianyu** [comment]
Chiming in here--exact same error as the above two comments:

`
Traceback (most recent call last):
  File "/opt/homebrew/bin/pyega3", line 8, in <module>
    sys.exit(main())
  File "/opt/homebrew/lib/python3.9/site-packages/pyega3/pyega3.py", line 666, in main
    download_dataset(credentials, args.identifier, args.connections, key, args.saveto, genomic_range_args,
  File "/opt/homebrew/lib/python3.9/site-packages/pyega3/pyega3.py", line 516, in download_dataset
    if (not dataset_id in api_list_authorized_datasets(token)):
  File "/opt/homebrew/lib/python3.9/site-packages/pyega3/pyega3.py", line 163, in api_list_authorized_datasets
    r.raise_for_status()
  File "/opt/homebrew/lib/python3.9/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error:  for url: https://ega.ebi.ac.uk:8052/elixir/data/metadata/datasets
`

**Comment by malloryfreeberg** [comment]
Hi all,
Thank you all for reporting these issues. `500 Server Error` errors usually mean a temporary connection issue, which usually resolves itself after a period of time. If you retry your downloads and are still experiencing this behavior, please email EGA Helpdesk at helpdesk@ega-archive.org with this issue and attach the output log produced by pyega3 (pyega3_output.log). The Helpdesk team can then provide further assistance for your individual cases. Thank you!

**Comment by malloryfreeberg** [comment]
I will close this ticket now, but if you encounter `500 Server Errors` again, please reach out to helpdesk@ega-archive.org.
