### ISSUE TITLE
"Invalid username" even when no credentials provided.

### ISSUE THREAD

**Issue by findlaycopley** [EGA-archive/ega-download-client#111]
I downloaded pyega3 earlier in the week whilst my request to access some files was approved. It was working fine using my credentials to log in and view avaliable datasets.

When I tried to download this dataset today I recieved the following error:

```
[2021-05-14 12:47:01 +0100] Invalid username, password or secret key - please check and retry. If problem persists contact helpdesk on helpdesk@ega-archive.org
Traceback (most recent call last):
  File "/home/findlay/.local/lib/python3.7/site-packages/pyega3/pyega3.py", line 144, in get_token
    reply = r.json()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

This happens using my account credentials, using the default credentials from the tutorial and even using no credentials file at all i.e. 
`pyega3 -d -t datasets`

I've tried this on two separate machines, both running different versions of python (python 3.7.3 and python 3.8.5) and both with fresh installs of pyega3.

Any idea why it's stopped working today?

**Comment by findlaycopley** [comment]
Seems to have sorted itself out!
