### ISSUE TITLE
Multiple errors while downloading multiple files

### ISSUE THREAD

**Issue by danarte** [EGA-archive/ega-download-client#113]
**Title of the bug** 

*Multiple different errors when downloading large dataset (15 TB) one file at a time*

**Description of the bug**

Hello,
We try to download a large dataset one file at a time, we download the file, process it and then delete it.
This process is set up with an automated pipeline (that uses the same machine and same credentials to download all files which should take a few days to complete. But for the past 3 weeks we are struggling and we needed to restart our workflow multiple times because many files simply do not complete/start the download.
For example in our last try, we still had 24 files to download, 4 files downloaded successfully, while 30 files failed for various reasons at different times.

Here are the examples of the failed downloads (the error logs are pasted below for each error respectively):
1. Failed md5 verification at the end (the file started downloading from zero, not continuing a failed download...)
2. Invalid password or username (with the same credential file as used successfully for other downloads)
3. Failing mid download
4. Failing authentication before starting download
5. 500 server error mid download
6. 504 error mid download

Those errors are very frustrating and we couldn't solve them by ourselves which left us the only option of rerunning the pipeline. Instead of downloading the files and continuing our research we are met with unsolvable multiple errors that require laborious manual work to correct and rerun our pipeline. 
We were supposed to finish downloading the dataset and start our analysis three weeks ago but instead we are forced to brutforce our way through those errors with still many files left to download.
Hope my feedback can help you troubleshoot those issues which will help us and other users to use the EGA platform without errors.

1.
```
[2021-07-01 19:26:10 +0300]
[2021-07-01 19:26:10 +0300] pyEGA3 - EGA python client version 3.4.0 (https://github.com/EGA-archive/ega-download-client)
[2021-07-01 19:26:10 +0300] Parts of this software are derived from pyEGA (https://github.com/blachlylab/pyega) by James Blachly
[2021-07-01 19:26:10 +0300] Python version : 3.5.1
[2021-07-01 19:26:10 +0300] OS version : Linux #1 SMP Wed May 4 00:57:44 UTC 2016
[2021-07-01 19:26:10 +0300] Server URL: https://ega.ebi.ac.uk:8052/elixir/data
[2021-07-01 19:26:10 +0300] Session-Id: 2909837551
[2021-07-01 19:26:13 +0300]
[2021-07-01 19:26:13 +0300] Authentication success for user 'XXXX'
[2021-07-01 19:26:26 +0300]
[2021-07-01 19:26:26 +0300] Authentication success for user 'XXXX'
[2021-07-01 19:26:26 +0300] File Id: 'EGAF00003940690'(92445114724 bytes).
[2021-07-01 19:26:26 +0300] Total space : 41830.40 GiB
[2021-07-01 19:26:26 +0300] Used space : 36677.46 GiB
[2021-07-01 19:26:26 +0300] Free space : 5152.94 GiB
[2021-07-01 19:26:26 +0300] Download starting [using 24 connection(s)]...
^M  0%|          | 0.00/92.4G [00:00<?, ?B/s]

...After many hours...

100%|##########| 92.4G/92.4G [38:01<00:00, 40.5MB/s]
[2021-07-02 15:27:22 +0300] Verifying file checksum
[2021-07-02 15:27:31 +0300] Download process expected md5 value 'da4330e059f41c40712782c347f2dbc2' but got '61ebf4e9f8d46274c2b3374f4fefcb64'
Traceback (most recent call last):
  File "/XXXX/.local/lib/python3.5/site-packages/pyega3/pyega3.py", line 494, in download_file_retry
    download_file(token, file_id, file_size, check_sum, num_connections, key, output_file)
  File "/XXXX/.local/lib/python3.5/site-packages/pyega3/pyega3.py", line 448, in download_file
    raise Exception("Download process expected md5 value '{}' but got '{}'".format(check_sum, received_file_md5))
Exception: Download process expected md5 value 'da4330e059f41c40712782c347f2dbc2' but got '61ebf4e9f8d46274c2b3374f4fefcb64'
Traceback (most recent call last):
  File "/XXXX/.local/bin//pyega3", line 8, in <module>
    sys.exit(main())
  File "/XXXX/.local/lib/python3.5/site-packages/pyega3/pyega3.py", line 672, in main
    args.saveto, genomic_range_args, args.max_retries, args.retry_wait)
  File "/XXXX/.local/lib/python3.5/site-packages/pyega3/pyega3.py", line 502, in download_file_retry
    raise e
  File "/XXXX/.local/lib/python3.5/site-packages/pyega3/pyega3.py", line 494, in download_file_retry
    download_file(token, file_id, file_size, check_sum, num_connections, key, output_file)
  File "/XXXX/.local/lib/python3.5/site-packages/pyega3/pyega3.py", line 448, in download_file
    raise Exception("Download process expected md5 value '{}' but got '{}'".format(check_sum, received_file_md5))
Exception: Download process expected md5 value 'da4330e059f41c40712782c347f2dbc2' but got '61ebf4e9f8d46274c2b3374f4fefcb64'
```

2.
```
[2021-07-02 11:16:54 +0300]
[2021-07-02 11:16:54 +0300] pyEGA3 - EGA python client version 3.4.0 (https://github.com/EGA-archive/ega-download-client)
[2021-07-02 11:16:54 +0300] Parts of this software are derived from pyEGA (https://github.com/blachlylab/pyega) by James Blachly
[2021-07-02 11:16:54 +0300] Python version : 3.5.1
[2021-07-02 11:16:54 +0300] OS version : Linux #1 SMP Wed Oct 26 06:52:09 UTC 2016
[2021-07-02 11:16:54 +0300] Server URL: https://ega.ebi.ac.uk:8052/elixir/data
[2021-07-02 11:16:54 +0300] Session-Id: 2631289112
[2021-07-02 11:17:54 +0300]
[2021-07-02 11:17:54 +0300] Invalid username, password or secret key - please check and retry. If problem persists contact helpdesk on helpdesk@ega-archive.org
Traceback (most recent call last):
  File "/XXX/.local/lib/python3.5/site-packages/pyega3/pyega3.py", line 144, in get_token
    reply = r.json()
  File "/share/apps/python/python351/lib/python3.5/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/share/apps/python/python351/lib/python3.5/site-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/share/apps/python/python351/lib/python3.5/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/share/apps/python/python351/lib/python3.5/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

3.
```
[2:38:25<2706:03:11, 6.00kB/s]^M 43%|####2     | 4
3.7G/102G [2:38:25<2214:58:19, 7.33kB/s]
[2021-07-02 11:13:02 +0300] Slice error: received=25357678, requested=4256361524, file='/XXXX/bam/EGAF00003935711/post-LUAD-26.bam-from-0-len-4256361524.slice'
Traceback (most recent call last):
  File "/XXXX/.local/lib/python3.5/site-packages/pyega3/pyega3.py", line 494, in download_file_retry
    download_file(token, file_id, file_size, check_sum, num_connections, key, output_file)
  File "/XXXX/.local/lib/python3.5/site-packages/pyega3/pyega3.py", line 422, in download_file
    for part_file_name in executor.map(download_file_slice_, params):
  File "/share/apps/python/python351/lib/python3.5/concurrent/futures/_base.py", line 556, in result_iterator
    yield future.result()
  File "/share/apps/python/python351/lib/python3.5/concurrent/futures/_base.py", line 405, in result
    return self.__get_result()
  File "/share/apps/python/python351/lib/python3.5/concurrent/futures/_base.py", line 357, in __get_result
    raise self._exception
  File "/share/apps/python/python351/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/XXXX/.local/lib/python3.5/site-packages/pyega3/pyega3.py", line 296, in download_file_slice_
    return download_file_slice(*args)
  File "/XXXX/.local/lib/python3.5/site-packages/pyega3/pyega3.py", line 290, in download_file_slice
    raise Exception("Slice error: received={}, requested={}, file='{}'".format(total_received, length, file_name))
Exception: Slice error: received=25357678, requested=4256361524, file='XXXX/bam/EGAF00003935711/post-LUAD-26.bam-from-0-len-4256361524.slice'
[2021-07-02 11:14:03 +0300] retry attempt 2
[2021-07-02 11:15:03 +0300]
[2021-07-02 11:15:03 +0300] Invalid username, password or secret key - please check and retry. If problem persists contact helpdesk on helpdesk@ega-archive.org
Traceback (most recent call last):
  File "/XXXX/.local/lib/python3.5/site-packages/pyega3/pyega3.py", line 144, in get_token
    reply = r.json()
  File "/share/apps/python/python351/lib/python3.5/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/share/apps/python/python351/lib/python3.5/site-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/share/apps/python/python351/lib/python3.5/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/share/apps/python/python351/lib/python3.5/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

4.
```
[2021-06-28 06:43:00 +0300]
[2021-06-28 06:43:00 +0300] pyEGA3 - EGA python client version 3.4.0 (https://github.com/EGA-archive/ega-download-client)
[2021-06-28 06:43:00 +0300] Parts of this software are derived from pyEGA (https://github.com/blachlylab/pyega) by James Blachly
[2021-06-28 06:43:00 +0300] Python version : 3.5.1
[2021-06-28 06:43:00 +0300] OS version : Linux #1 SMP Wed Oct 26 06:52:09 UTC 2016
[2021-06-28 06:43:00 +0300] Server URL: https://ega.ebi.ac.uk:8052/elixir/data
[2021-06-28 06:43:00 +0300] Session-Id: 3838796778
[2021-06-28 06:43:05 +0300]
[2021-06-28 06:43:05 +0300] Authentication success for user 'XXXX'
Traceback (most recent call last):
  File "/XXXX/.local/bin//pyega3", line 8, in <module>
    sys.exit(main())
  File "/XXXX/.local/lib/python3.5/site-packages/pyega3/pyega3.py", line 670, in main
    display_file_name, file_name, file_size, check_sum = get_file_name_size_md5(token, args.identifier)
  File "/XXXX/.local/lib/python3.5/site-packages/pyega3/pyega3.py", line 250, in get_file_name_size_md5
    r.raise_for_status()
  File "/share/apps/python/python351/lib/python3.5/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error:  for url: https://ega.ebi.ac.uk:8052/elixir/data/metadata/files/EGAF00003940673

```
5.
```
56%|#####5    | 55.1G/99.3G [01:43<01:23, 531MB/s]
[2021-06-22 21:58:27 +0300] 500 Server Error:  for url: https://ega.ebi.ac.uk:8052/elixir/data/files/EGAF00003940659?destinationFormat=plain
Traceback (most recent call last):
  File "/XXX/.local/lib/python3.5/site-packages/pyega3/pyega3.py", line 494, in download_file_retry
    download_file(token, file_id, file_size, check_sum, num_connections, key, output_file)
  File "/XXXX/.local/lib/python3.5/site-packages/pyega3/pyega3.py", line 422, in download_file
    for part_file_name in executor.map(download_file_slice_, params):
  File "/share/apps/python/python351/lib/python3.5/concurrent/futures/_base.py", line 556, in result_iterator
    yield future.result()
  File "/share/apps/python/python351/lib/python3.5/concurrent/futures/_base.py", line 405, in result
    return self.__get_result()
  File "/share/apps/python/python351/lib/python3.5/concurrent/futures/_base.py", line 357, in __get_result
    raise self._exception
  File "/share/apps/python/python351/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/XXXX/.local/lib/python3.5/site-packages/pyega3/pyega3.py", line 296, in download_file_slice_
    return download_file_slice(*args)
  File "/XXXX/.local/lib/python3.5/site-packages/pyega3/pyega3.py", line 282, in download_file_slice
    r.raise_for_status()
  File "/share/apps/python/python351/lib/python3.5/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error:  for url: https://ega.ebi.ac.uk:8052/elixir/data/files/EGAF00003940659?destinationFormat=plain
Traceback (most recent call last):
  File "/XXX/.local/bin//pyega3", line 8, in <module>
    sys.exit(main())
  File "/XXX/.local/lib/python3.5/site-packages/pyega3/pyega3.py", line 672, in main
    args.saveto, genomic_range_args, args.max_retries, args.retry_wait)
  File "/XXXX/.local/lib/python3.5/site-packages/pyega3/pyega3.py", line 502, in download_file_retry
    raise e
  File "/XXX/.local/lib/python3.5/site-packages/pyega3/pyega3.py", line 494, in download_file_retry
    download_file(token, file_id, file_size, check_sum, num_connections, key, output_file)
  File "/XXXX/.local/lib/python3.5/site-packages/pyega3/pyega3.py", line 422, in download_file
    for part_file_name in executor.map(download_file_slice_, params):
  File "/share/apps/python/python351/lib/python3.5/concurrent/futures/_base.py", line 556, in result_iterator
    yield future.result()
  File "/share/apps/python/python351/lib/python3.5/concurrent/futures/_base.py", line 405, in result
    return self.__get_result()
  File "/share/apps/python/python351/lib/python3.5/concurrent/futures/_base.py", line 357, in __get_result
    raise self._exception
  File "/share/apps/python/python351/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/XXXX/.local/lib/python3.5/site-packages/pyega3/pyega3.py", line 296, in download_file_slice_
    return download_file_slice(*args)
  File "/XXXX/.local/lib/python3.5/site-packages/pyega3/pyega3.py", line 282, in download_file_slice
    r.raise_for_status()
  File "/share/apps/python/python351/lib/python3.5/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error:  for url: https://ega.ebi.ac.uk:8052/elixir/data/files/EGAF00003940659?destinationFormat=plain
```
6.
```
  93%|#########3| 88.6G/95.0G [2:00:53<1416:32:54, 1.27kB/s]
  [2021-07-02 10:21:01 +0300] 504 Server Error:  for url: https://ega.ebi.ac.uk:8052/elixir/data/files/EGAF00003940675?destinationFormat=plain
  Traceback (most recent call last):
  File "/XXXX/.local/lib/python3.5/site-packages/pyega3/pyega3.py", line 494, in download_file_retry
    download_file(token, file_id, file_size, check_sum, num_connections, key, output_file)
  File "/XXXX/.local/lib/python3.5/site-packages/pyega3/pyega3.py", line 422, in download_file
    for part_file_name in executor.map(download_file_slice_, params):
  File "/share/apps/python/python351/lib/python3.5/concurrent/futures/_base.py", line 556, in result_iterator
    yield future.result()
  File "/share/apps/python/python351/lib/python3.5/concurrent/futures/_base.py", line 405, in result
    return self.__get_result()
  File "/share/apps/python/python351/lib/python3.5/concurrent/futures/_base.py", line 357, in __get_result
    raise self._exception
  File "/share/apps/python/python351/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/XXXX/.local/lib/python3.5/site-packages/pyega3/pyega3.py", line 296, in download_file_slice_
    return download_file_slice(*args)
  File "/XXXX/.local/lib/python3.5/site-packages/pyega3/pyega3.py", line 282, in download_file_slice
    r.raise_for_status()
  File "/share/apps/python/python351/lib/python3.5/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 504 Server Error:  for url: https://ega.ebi.ac.uk:8052/elixir/data/files/EGAF00003940675?destinationFormat=plain
Traceback (most recent call last):
  File "/XXXX/.local/bin//pyega3", line 8, in <module>
    sys.exit(main())
  File "/XXXX/.local/lib/python3.5/site-packages/pyega3/pyega3.py", line 672, in main
    args.saveto, genomic_range_args, args.max_retries, args.retry_wait)
  File "/XXXX/.local/lib/python3.5/site-packages/pyega3/pyega3.py", line 502, in download_file_retry
    raise e
  File "/XXXX/.local/lib/python3.5/site-packages/pyega3/pyega3.py", line 494, in download_file_retry
    download_file(token, file_id, file_size, check_sum, num_connections, key, output_file)
  File "/XXXX/.local/lib/python3.5/site-packages/pyega3/pyega3.py", line 422, in download_file
    for part_file_name in executor.map(download_file_slice_, params):
  File "/share/apps/python/python351/lib/python3.5/concurrent/futures/_base.py", line 556, in result_iterator
    yield future.result()
  File "/share/apps/python/python351/lib/python3.5/concurrent/futures/_base.py", line 405, in result
    return self.__get_result()
  File "/share/apps/python/python351/lib/python3.5/concurrent/futures/_base.py", line 357, in __get_result
    raise self._exception
  File "/share/apps/python/python351/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/XXXX/.local/lib/python3.5/site-packages/pyega3/pyega3.py", line 296, in download_file_slice_
    return download_file_slice(*args)
  File "/XXXX/.local/lib/python3.5/site-packages/pyega3/pyega3.py", line 282, in download_file_slice
    r.raise_for_status()
  File "/share/apps/python/python351/lib/python3.5/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 504 Server Error:  for url: https://ega.ebi.ac.uk:8052/elixir/data/files/EGAF00003940675?destinationFormat=plain
```

**Comment by danielbruhm** [comment]
I'm having the same issue downloading a set of roughly 50 bam files each ~100GB. Usually the download fails with one of the error messages mentioned above but if I restart the download enough times eventually it will finish successfully. After 2-3 weeks of that about 50% of the files have downloaded successfully.

**Comment by supernifty** [comment]
Just to add that I am having the same problem. I have 20 bam files to download each ~50GB. After about a week I am still on the first file! Ongoing 5xx errors and mismatched MD5 sums. I emailed EGA support for help but so far no reply.

**Comment by danarte** [comment]
Hello,
I'm wondering if this issue is being worked on? we are still having trouble downloading large datasets.

**Comment by malloryfreeberg** [comment]
Thank you for reporting these issues. I apologise that you are experiencing them and that they are causing downloads to take longer than expected. We are in the processing of testing a new version of our data download API (which pyega3 uses) which we hope will provide a more reliable and stable service, so that you can download files more quickly from EGA. Your patience while we get the new API into production is greatly appreciated!

**Comment by danarte** [comment]
> Thank you for reporting these issues. I apologise that you are experiencing them and that they are causing downloads to take longer than expected. We are in the processing of testing a new version of our data download API (which pyega3 uses) which we hope will provide a more reliable and stable service, so that you can download files more quickly from EGA. Your patience while we get the new API into production is greatly appreciated!

We are still struggling with this, with the slow download speed (1-15 MB/s) and the constant errors we are downloading on average 2-3 files per day which is just unrealistic speed when we have a 150 file dataset to download.

@malloryfreeberg  Please let as know as soon as possible when the new version is available.

**Comment by nstitziel** [comment]
I too am having repeated server errors (504) that is preventing the download of a large critical file needed for our analysis. I have been trying for over 1 week and have 99% of the file downloaded but the last part is constantly failing with error 504. Not a problem to download other smaller files.

**Comment by ValerieMarot** [comment]
I am experiencing the same issue, even when trying to download the test file or any other small files. The downloads were still working a few weeks ago but now I cannot download any files without error 504.

**Comment by ImFran** [comment]
Hi everyone!
I started my downloads in EGA about 2 weeks ago and I successfully downloaded very small text files. Unfortunately, I am still experiencing the same error 504 (DestinationFormat=plain) for larger files... Any news about the client new version?

**Comment by Anneilse** [comment]
Hi everyone, me too I am still experiencing exactly the same problems when downloading files (10-20GB) each. Most of them fail due to wrong md5sums or are not fully downloaded (We are left with slices of the bam files but no complete files). I would be very happy to get news on the new client or a way to resolve the situation.

**Comment by erojoa** [comment]
Trying to download an EGAD containing 5268 files/EGAFs (total size slightly above 2TB) but keep on getting errors when attempting to fetch everything at once. I contacted the helpdesk earlier but have so far received no reply. I can see this has been an issue for over a year now, so any assistance would be greatly appreciated. Thank you very much.

**Comment by dkasd** [comment]
Same here, trying to download an EGAD we got access to after a lengthy process, and it is almost impossible to download files. Same issues  as other users are reporting above (several of them, sometimes 504, sometimes 500, sometimes downloads that get stuck at ~90%) even for the test datasets, and from 3 different HPC servers. Awfully random behavior overall. It is really frustrating as compared to similar services with really high traffic (e.g. dbgap) and that work without issues. I hope EGA is working on this. Thanks

**Comment by Venkataragavan** [comment]
I still face this issue. I am trying to download one fastq file of ~5GB, which downloads completely, and then errors out with mismatches md5 checksums. I have attached the error log here.

[error_log.txt](https://github.com/EGA-archive/ega-download-client/files/10792612/error_log.txt)

**Comment by EricPerser** [comment]
After 2 years of complaints by users, I'm wondering why EGA are still insisting on imposing a tool which is simply incapable of delivering. After long waiting times of getting access to controlled data, it is impossible to download a single file pain-free.

**Comment by tk2** [comment]
Hi All, the backend system for the real-time streaming downloader is complicated with multiple infrastructure dependencies and susceptible to contention - some of which are out of the control of the EGA team. We can offer alternative asynchronous download methods, please contact the EGA helpdesk (ega-helpdesk@ebi.ac.uk) to arrange.
