### ISSUE TITLE
speed optimization

### ISSUE THREAD

**Issue by chrishuges** [EGA-archive/ega-download-client#121]
**Speed optimization** 

Experiencing slow speeds with dataset EGAD00001004493. Similar issue to [#27](https://github.com/EGA-archive/ega-download-client/issues/27).

**Description of the bug**

I have a script that downloads the files associated with one patient from this dataset, analyzes it, then deletes it and moves on to the next. However, no matter how many --connections I tell it to use (from 5 to 50 for example), I never seem to experience speeds greater than 2MB/s (and frequently much slower). I frequently download files from SRA on this same machine at much higher speeds without issue. Is there something else I can try to increase this speed? Or is there something wrong with this specific dataset?

**Used versions** (please complete the following information)
 - Operating System version: CentOS7
 - Python version: 3.6.8
 - PyEGA3 version: 3.4.1
 - Please, **confirm you have tested your PyEGA3 installation** (follow [instructions](https://github.com/EGA-archive/ega-download-client#testing-pyega3-installation#Testing-pyEGA3-installation)): Yes.

My issue does appear in the Troubleshooting, but the connections argument doesn't seem to have any benefit.

**To Reproduce**

Try downloading an RNA-seq file from the above mentioned dataset.

**Comment by chrishuges** [comment]
I was able to mostly "resolve" this by just writing a script that continuously repeats the file downloads until it successfully completes. The downloads still fail extremely frequently (basically needs 2 or 3 retries on each) and the speeds are generally slower than I would expect (2MB/s), but it works eventually. 

An example of the error I see most often:

```
[2021-09-22 12:25:03 -0700] retry attempt 1
[2021-09-22 12:25:03 -0700] Download starting [using 10 connection(s)]...
 70%|######9   | 328M/468M [02:43<01:09, 2.01MB/s]
[2021-09-22 12:27:46 -0700] 500 Server Error:  for url: https://ega.ebi.ac.uk:8052/elixir/data/files/EGAF00002258661?destinationFormat=plain
Traceback (most recent call last):
  File "/home/chughes/virtualPython368/lib64/python3.6/site-packages/pyega3/pyega3.py", line 494, in download_file_retry
    download_file(token, file_id, file_size, check_sum, num_connections, key, output_file)
  File "/home/chughes/virtualPython368/lib64/python3.6/site-packages/pyega3/pyega3.py", line 422, in download_file
    for part_file_name in executor.map(download_file_slice_, params):
  File "/usr/lib64/python3.6/concurrent/futures/_base.py", line 586, in result_iterator
    yield fs.pop().result()
  File "/usr/lib64/python3.6/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/lib64/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/lib64/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/chughes/virtualPython368/lib64/python3.6/site-packages/pyega3/pyega3.py", line 296, in download_file_slice_
    return download_file_slice(*args)
  File "/home/chughes/virtualPython368/lib64/python3.6/site-packages/pyega3/pyega3.py", line 282, in download_file_slice
    r.raise_for_status()
  File "/home/chughes/virtualPython368/lib64/python3.6/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error:  for url: https://ega.ebi.ac.uk:8052/elixir/data/files/EGAF00002258661?destinationFormat=plain
[2021-09-22 12:28:46 -0700] retry attempt 2
```

It will retry this 5 times, but then gives up. But, by restarting it with the script it eventually gets it done.

**Comment by danarte** [comment]
@chrishuges Could you please share the script? I'm wondering how did you check the completion status... 
We are having trouble downloading a large dataset (15TB) and I think with the current rate of errors and fails it will take us about a year to download with manual monitoring and restarts of the download when it fails...

**Comment by malloryfreeberg** [comment]
Hi there! We have made some improvements to pyega3 that address this issue and have merged these changes into master. If you [install pyega3 from GitHub](https://github.com/EGA-archive/ega-download-client#using-github) you should be able to take advantage of these updates. We have not yet done a full version release, but when we do, these features will also be available from pip3/conda install. Thank you for your patience while we improved pyega3!

**Comment by chrishuges** [comment]
Thank you for the update! The new tool works much better and I am no longer having issues with it.

**Comment by malloryfreeberg** [comment]
Hi @chrishuges - Thank you so much for the feedback, and glad to hear the tool is working better for you!
