### ISSUE TITLE
Display correct error message instead of "Invalid username, password or secret key" for fresh accounts

### ISSUE THREAD

**Issue by ghuls** [EGA-archive/ega-download-client#146]
**Title of the bug**

Display correct error message instead of "Invalid username, password or secret key" for fresh accounts

**Description of the bug**

Display a correct error message instead of "Invalid username, password or secret key" for fresh accounts when the username and password is correct (works on the website), but the account is maybe not fully functional yet.

The token function in pyega3/libs/auth_client.py returns a JSON message:
```
{'message': 'Unable to process request at this moment'}
```
but will display "Invalid username, password or secret key - please check and retry. If problem persists contact helpdesk on helpdesk@ega-archive.org", which is quite confusing.

```
❯  pyega3 -cf pyega3.json -d datasets
[2022-03-17 16:30:18 +0100]
[2022-03-17 16:30:18 +0100] pyEGA3 - EGA python client version 4.0.0 (https://github.com/EGA-archive/ega-download-client)
[2022-03-17 16:30:18 +0100] Parts of this software are derived from pyEGA (https://github.com/blachlylab/pyega) by James Blachly
[2022-03-17 16:30:18 +0100] Python version : 3.10.2
[2022-03-17 16:30:18 +0100] OS version : Linux #1 SMP Tue Sep 7 14:49:57 UTC 2021
[2022-03-17 16:30:18 +0100] Server URL: https://ega.ebi.ac.uk:8052/elixir/data
[2022-03-17 16:30:18 +0100] Session-Id: 320916844
[2022-03-17 16:30:18 +0100] Starting new HTTPS connection (1): ipinfo.io:443
[2022-03-17 16:30:18 +0100] https://ipinfo.io:443 "GET /json HTTP/1.1" 200 None
https://ega.ebi.ac.uk:8443/ega-openid-connect-server/token
[2022-03-17 16:30:18 +0100] Starting new HTTPS connection (1): ega.ebi.ac.uk:8443
[2022-03-17 16:30:18 +0100] https://ega.ebi.ac.uk:8443 "POST /ega-openid-connect-server/token HTTP/1.1" 500 54
{'message': 'Unable to process request at this moment'}
[2022-03-17 16:30:18 +0100]
[2022-03-17 16:30:18 +0100] Invalid username, password or secret key - please check and retry. If problem persists contact helpdesk on helpdesk@ega-archive.org
```

**Comment by jianguozhouzunyimedicaluniversity** [comment]
I also have the same error....
```
(pyega3) [zhou@localhost STAR]$ pyega3 -cf ~/raid/EGA/zjg.zmu_credential_file.json datasets
[2022-03-18 04:30:29 +0800] 
[2022-03-18 04:30:29 +0800] pyEGA3 - EGA python client version 4.0.0 (https://github.com/EGA-archive/ega-download-client)
[2022-03-18 04:30:29 +0800] Parts of this software are derived from pyEGA (https://github.com/blachlylab/pyega) by James Blachly
[2022-03-18 04:30:29 +0800] Python version : 3.8.12
[2022-03-18 04:30:29 +0800] OS version : Linux #1 SMP Fri Jan 14 13:59:45 UTC 2022
[2022-03-18 04:30:29 +0800] Server URL: https://ega.ebi.ac.uk:8052/elixir/data
[2022-03-18 04:30:29 +0800] Session-Id: 1207189894
[2022-03-18 04:30:30 +0800] 
[2022-03-18 04:30:30 +0800] Invalid username, password or secret key - please check and retry. If problem persists contact helpdesk on helpdesk@ega-archive.org
Traceback (most recent call last):
  File "/home/zhou/miniconda2/envs/pyega3/lib/python3.8/site-packages/pyega3/libs/auth_client.py", line 38, in token
    r.raise_for_status()
  File "/home/zhou/miniconda2/envs/pyega3/lib/python3.8/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error:  for url: https://ega.ebi.ac.uk:8443/ega-openid-connect-server/token
```

**Comment by young315** [comment]
> I also have the same error....
> 
> ```
> (pyega3) [zhou@localhost STAR]$ pyega3 -cf ~/raid/EGA/zjg.zmu_credential_file.json datasets
> [2022-03-18 04:30:29 +0800] 
> [2022-03-18 04:30:29 +0800] pyEGA3 - EGA python client version 4.0.0 (https://github.com/EGA-archive/ega-download-client)
> [2022-03-18 04:30:29 +0800] Parts of this software are derived from pyEGA (https://github.com/blachlylab/pyega) by James Blachly
> [2022-03-18 04:30:29 +0800] Python version : 3.8.12
> [2022-03-18 04:30:29 +0800] OS version : Linux #1 SMP Fri Jan 14 13:59:45 UTC 2022
> [2022-03-18 04:30:29 +0800] Server URL: https://ega.ebi.ac.uk:8052/elixir/data
> [2022-03-18 04:30:29 +0800] Session-Id: 1207189894
> [2022-03-18 04:30:30 +0800] 
> [2022-03-18 04:30:30 +0800] Invalid username, password or secret key - please check and retry. If problem persists contact helpdesk on helpdesk@ega-archive.org
> Traceback (most recent call last):
>   File "/home/zhou/miniconda2/envs/pyega3/lib/python3.8/site-packages/pyega3/libs/auth_client.py", line 38, in token
>     r.raise_for_status()
>   File "/home/zhou/miniconda2/envs/pyega3/lib/python3.8/site-packages/requests/models.py", line 960, in raise_for_status
>     raise HTTPError(http_error_msg, response=self)
> requests.exceptions.HTTPError: 500 Server Error:  for url: https://ega.ebi.ac.uk:8443/ega-openid-connect-server/token
> ```
"Invalid username, password or secret key - please check and retry." I have the same trouble either.

**Comment by malloryfreeberg** [comment]
Thanks @ghuls for the suggestion! You are right that it is a good idea to make sure the error messages returned reflect the real issue. I will raise your suggestion with our development team. 

In the meantime, we ask anyone experiencing issues with their account to please email the EGA Helpdesk at [helpdesk@ega-archive.org](mailto:helpdesk@ega-archive.org) with this issue and attach the output log produced by pyega3 (pyega3_output.log). The Helpdesk team can then provide further assistance for your specific account. Thank you.

**Comment by jianguozhouzunyimedicaluniversity** [comment]
````
2022-06-26 04:44:43 +0200] Invalid username, password or secret key - please check and retry. If problem persists contact helpdesk on helpdesk@ega-archive.org
Traceback (most recent call last):
  File "/root/miniconda3/envs/pyega3/lib/python3.8/site-packages/pyega3/libs/auth_client.py", line 38, in token
    r.raise_for_status()
  File "/root/miniconda3/envs/pyega3/lib/python3.8/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error:  for url: https://ega.ebi.ac.uk:8443/ega-openid-connect-server/token
[2022-06-26 04:44:47 +0200] 
[2022-06-26 04:44:47 +0200] pyEGA3 - EGA python client version 4.0.0 (https://github.com/EGA-archive/ega-download-client)
[2022-06-26 04:44:47 +0200] Parts of this software are derived from pyEGA (https://github.com/blachlylab/pyega) by James Blachly
[2022-06-26 04:44:47 +0200] Python version : 3.8.13
[2022-06-26 04:44:47 +0200] OS version : Linux #123-Ubuntu SMP Fri Apr 8 09:10:54 UTC 2022
[2022-06-26 04:44:47 +0200] Server URL: https://ega.ebi.ac.uk:8052/elixir/data
[2022-06-26 04:44:47 +0200] Session-Id: 4020903282
[2022-06-26 04:44:53 +0200] 
[2022-06-26 04:44:53 +0200] Invalid username, password or secret key - please check and retry. If problem persists contact helpdesk on helpdesk@ega-archive.org
Traceback (most recent call last):
  File "/root/miniconda3/envs/pyega3/lib/python3.8/site-packages/pyega3/libs/auth_client.py", line 38, in token
    r.raise_for_status()
  File "/root/miniconda3/envs/pyega3/lib/python3.8/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error:  for url: https://ega.ebi.ac.uk:8443/ega-openid-connect-server/token
[2022-06-26 04:44:57 +0200] 
[2022-06-26 04:44:57 +0200] Invalid username, password or secret key - please check and retry. If problem persists contact helpdesk on helpdesk@ega-archive.org
Traceback (most recent call last):
  File "/root/miniconda3/envs/pyega3/lib/python3.8/site-packages/pyega3/libs/auth_client.py", line 38, in token
    r.raise_for_status()
  File "/root/miniconda3/envs
````

**Comment by CsabaHalmagyi** [comment]
Authentication issues have been resolved with the release of the new data api. Closing.
