### ISSUE TITLE
EGA client not able to download all the files within a dataset 

### ISSUE THREAD

**Issue by chriss1313** [EGA-archive/ega-download-client#147]
Invalid username and premature stopping of download. 
Files stop downloading after a certain point and stop downloading subsequent data that has yet to be downloaded. 

I recently got access to an EGA dataset. I have been using the pyega3 client to download files from the dataset. The dataset is fairly large, with about 8,700 files. However, only 936 files are downloaded (EGAF folders with raw data and md5 file). I am unsure why my download stops prematurely. The last time I tried downloading I ran into a similar issue, this most recent time I ran with 15 connections and that seemed to work better.   

After downloading 936 files, I get this error: 
[2022-04-01 16:59:41 -0400] Invalid username, password or secret key - please check and retry. If problem persists contact helpdesk on helpdesk@ega-archive.org
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pyega3/libs/auth_client.py", line 37, in token
    reply = r.json()
  File "/usr/local/lib/python3.8/dist-packages/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

I used the most recent version and followed the instructions for installation posted on this GitHub page. 

I'm running python3. 

I tested the connections before starting. 

I will attach the output.log file. 

[pyega3_output.log](https://github.com/EGA-archive/ega-download-client/files/8401187/pyega3_output.log)

**Comment by chriss1313** [comment]
Kyle,
Thanks so much for the reply. I checked through the folder and you're
correct, some of the downloaded files had no contents. However, this did
not prematurely stop the download as there were other files afterwards that
were downloaded fine. WhenI I compared the two runs I did, there were
different files that failed to download, so it seems random. Is there a way
to resume where I left off if a previous run fails midway? I've also
contacted EGA helpdesk directly and they said they would try to open an
Aspera box for my download.
I will try running again with --max-retries=-1
Thanks so much for the reply.



Best,
Chris Cardona

**Comment by malloryfreeberg** [comment]
Hi @chriss1313 

Thank you for reporting this issue. The download service is now more stable and reliable, so we hope you can finish downloading the dataset with few retries and empty files.

I will close this issue for now, but if you continue to experience issues downloading then please do reach out to the EGA Helpdesk at [helpdesk@ega-archive.org](mailto:helpdesk@ega-archive.org) with the output log produced by pyega3.

**Comment by chriss1313** [comment]
Kyle,
Sorry for the consecutive emails. I also wanted to ask if it is advisable
to change the parameters on -ms MAX_SLICE_SIZE? I see the default as 100
MB, what would be a good number to use for this parameter? What is the
formatting when using it in the command line (-ms 1000)?
I really appreciate all your help with this.



Best,
Chris Cardona
