### ISSUE TITLE
PyEGA downloads one chunk and reports download is complete

### ISSUE THREAD

**Issue by JasperO98** [EGA-archive/ega-download-client#175]
When I try to download a chromosome 17 for the BAM file EGAF00005572869 it is raising a 500 server error and then only downloads a single chunk. However, it reports that the download is completed. The bai file is available for the dataset.

Used versions

Windows 10 Enterprise 21H1
Python version: 3.9.12 (conda)
PyEGA3 version: 4.0.5 (conda)
I tested my PyEGA3 using the test datasets

Command:
`pyega3 -cf ../ega_credentials.json fetch --output-dir . -r 17 EGAF00005572869`

Files:
```
EGAF00005572869	1	236223215336	ef793ec4a95bb405232909a1da2aef41	Case5_IC.bam
EGAF00005572870	1	8915048	55cd778db0b822578699aaa4577230af	Case5_IC.bam.bai
```

Log:
```
[2022-10-12 13:58:25 +0200] pyEGA3 - EGA python client version 4.0.5 (https://github.com/EGA-archive/ega-download-client)
[2022-10-12 13:58:25 +0200] Parts of this software are derived from pyEGA (https://github.com/blachlylab/pyega) by James Blachly
[2022-10-12 13:58:25 +0200] Python version : 3.9.12
[2022-10-12 13:58:25 +0200] OS version : Linux #1 SMP Wed Mar 2 00:30:59 UTC 2022
[2022-10-12 13:58:25 +0200] Server URL: https://ega.ebi.ac.uk:8052/elixir/data
[2022-10-12 13:58:25 +0200] Session-Id: 2312431485
[2022-10-12 13:58:25 +0200]
[2022-10-12 13:58:25 +0200] Authentication success for user 'j.ouwerkerk.1@erasmusmc.nl'
[2022-10-12 13:59:20 +0200] File Id: 'EGAF00005572869'(236223215336 bytes).
[2022-10-12 13:59:20 +0200] Total space : 7452.02 GiB
[2022-10-12 13:59:20 +0200] Used space : 1372.69 GiB
[2022-10-12 13:59:20 +0200] Free space : 6079.33 GiB
[2022-10-12 14:00:21 +0200] Error: '500 Server Error:  for url: https://ega.ebi.ac.uk:8052/elixir/data/files/byid/file?accession=EGAF00005572869&format=BAM&chr=17' occured; sleeping 60s before retrying (attempt=1)
[2022-10-12 14:02:21 +0200] Error: '500 Server Error:  for url: https://ega.ebi.ac.uk:8052/elixir/data/files/byid/file?accession=EGAF00005572869&format=BAM&chr=17' occured; sleeping 60s before retrying (attempt=2)
[2022-10-12 14:04:21 +0200] Error: '500 Server Error:  for url: https://ega.ebi.ac.uk:8052/elixir/data/files/byid/file?accession=EGAF00005572869&format=BAM&chr=17' occured; sleeping 60s before retrying (attempt=3)
[2022-10-12 14:06:21 +0200] Error: '500 Server Error:  for url: https://ega.ebi.ac.uk:8052/elixir/data/files/byid/file?accession=EGAF00005572869&format=BAM&chr=17' occured; sleeping 60s before retrying (attempt=4)
[2022-10-12 14:08:24 +0200] Error: '500 Server Error:  for url: https://ega.ebi.ac.uk:8052/elixir/data/files/byid/file?accession=EGAF00005572869&format=BAM&chr=17' occured; sleeping 60s before retrying (attempt=5)
[2022-10-12 14:10:24 +0200] Error: '500 Server Error:  for url: https://ega.ebi.ac.uk:8052/elixir/data/files/byid/file?accession=EGAF00005572869&format=BAM&chr=17' occured; sleeping 60s before retrying (attempt=6)
[2022-10-12 14:12:34 +0200] Error: '500 Server Error:  for url: https://ega.ebi.ac.uk:8052/elixir/data/files/byid/file?accession=EGAF00005572869&format=BAM&chr=17' occured; sleeping 60s before retrying (attempt=7)
[2022-10-12 14:14:40 +0200] Error: '500 Server Error:  for url: https://ega.ebi.ac.uk:8052/elixir/data/files/byid/file?accession=EGAF00005572869&format=BAM&chr=17' occured; sleeping 60s before retrying (attempt=8)
[2022-10-12 14:16:49 +0200] Error: '500 Server Error:  for url: https://ega.ebi.ac.uk:8052/elixir/data/files/byid/file?accession=EGAF00005572869&format=BAM&chr=17' occured; sleeping 60s before retrying (attempt=9)
[2022-10-12 14:18:43 +0200] Error: '500 Server Error:  for url: https://ega.ebi.ac.uk:8052/elixir/data/files/byid/file?accession=EGAF00005572869&format=BAM&chr=17' occured; sleeping 60s before retrying (attempt=10)
[2022-10-12 14:22:02 +0200] Downloaded 20.2 MiB chunk in 139.05 seconds @ 0.14 MiB/s
[2022-10-12 14:22:02 +0200] Saved to : '/mnt/e/CINECA/htsget/small/EGAF00005572869/Case5_IC_genomic_range_17_None_None.bam'(21133367 bytes, referenceName=17, referenceMD5=None, start=None, end=None, format=BAM)
[2022-10-12 14:22:02 +0200] Download complete
```

It also doesn't work for the test dataset EGAD00001003338 on file the EGAF00007243777 with the default EGA credentials. However it does not download a chunk.

Command:
`pyega3 -cf ../default_ega_credentials.json fetch --output-dir . -r chr3 EGAF00007243777`

Files:
```
EGAF00007243777	1	122474	eee2883c95d3cd707961c80b6e44ee68	HG01500.GRCh38DH__90r__3.10000-10500__4.10000-10500.bam
EGAF00007243781	1	27104	10bc4d1dc9ca944339da830e4c868857	HG01500.GRCh38DH__90r__3.10000-10500__4.10000-10500.bam.bai
```

Log:
```
[2022-10-18 10:44:18 +0200]
[2022-10-18 10:44:18 +0200] pyEGA3 - EGA python client version 4.0.5 (https://github.com/EGA-archive/ega-download-client)
[2022-10-18 10:44:18 +0200] Parts of this software are derived from pyEGA (https://github.com/blachlylab/pyega) by James Blachly
[2022-10-18 10:44:18 +0200] Python version : 3.9.12
[2022-10-18 10:44:18 +0200] OS version : Linux #1 SMP Wed Mar 2 00:30:59 UTC 2022
[2022-10-18 10:44:18 +0200] Server URL: https://ega.ebi.ac.uk:8052/elixir/data
[2022-10-18 10:44:18 +0200] Session-Id: 1448198480
[2022-10-18 10:44:19 +0200]
[2022-10-18 10:44:19 +0200] Authentication success for user 'ega-test-data@ebi.ac.uk'

[2022-10-18 10:48:17 +0200] File Id: 'EGAF00007243777'(122474 bytes).
[2022-10-18 10:48:17 +0200] Total space : 7452.02 GiB
[2022-10-18 10:48:17 +0200] Used space : 2504.62 GiB
[2022-10-18 10:48:17 +0200] Free space : 4947.40 GiB
[2022-10-18 10:49:17 +0200] Error: '500 Server Error:  for url: https://ega.ebi.ac.uk:8052/elixir/data/files/byid/file?accession=EGAF00007243777&format=BAM&chr=chr3' occured; sleeping 60s before retrying (attempt=1)
[2022-10-18 10:51:17 +0200] Error: '500 Server Error:  for url: https://ega.ebi.ac.uk:8052/elixir/data/files/byid/file?accession=EGAF00007243777&format=BAM&chr=chr3' occured; sleeping 60s before retrying (attempt=2)
[2022-10-18 10:53:17 +0200] Error: '500 Server Error:  for url: https://ega.ebi.ac.uk:8052/elixir/data/files/byid/file?accession=EGAF00007243777&format=BAM&chr=chr3' occured; sleeping 60s before retrying (attempt=3)
[2022-10-18 10:56:18 +0200] Error: 'HTTPSConnectionPool(host='ega.ebi.ac.uk', port=8052): Read timed out. (read timeout=120)' occured; sleeping 60s before retrying (attempt=4)
[2022-10-18 10:58:18 +0200] Error: '500 Server Error:  for url: https://ega.ebi.ac.uk:8052/elixir/data/files/byid/file?accession=EGAF00007243777&format=BAM&chr=chr3' occured; sleeping 60s before retrying (attempt=5)
Traceback (most recent call last):
  File "/home/jasper/anaconda3/lib/python3.9/site-packages/htsget/io.py", line 94, in __get
    response.raise_for_status()
  File "/home/jasper/anaconda3/lib/python3.9/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error:  for url: https://ega.ebi.ac.uk:8052/elixir/data/files/byid/file?accession=EGAF00007243777&format=BAM&chr=chr3

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jasper/anaconda3/bin/pyega3", line 10, in <module>
    sys.exit(main())
  File "/home/jasper/anaconda3/lib/python3.9/site-packages/pyega3/pyega3.py", line 148, in main
    execute_subcommand(args, data_client)
  File "/home/jasper/anaconda3/lib/python3.9/site-packages/pyega3/libs/commands.py", line 22, in execute_subcommand
    fetch_data(args, data_client)
  File "/home/jasper/anaconda3/lib/python3.9/site-packages/pyega3/libs/commands.py", line 49, in fetch_data
    file.download_file_retry(num_connections=args.connections,
  File "/home/jasper/anaconda3/lib/python3.9/site-packages/pyega3/libs/data_file.py", line 288, in download_file_retry
    htsget.get(
  File "/home/jasper/anaconda3/lib/python3.9/site-packages/htsget/io.py", line 80, in get
    manager.run()
  File "/home/jasper/anaconda3/lib/python3.9/site-packages/htsget/protocol.py", line 147, in run
    self.__retry(self._handle_http_url, urlunparse(url), headers)
  File "/home/jasper/anaconda3/lib/python3.9/site-packages/htsget/protocol.py", line 123, in __retry
    raise re
  File "/home/jasper/anaconda3/lib/python3.9/site-packages/htsget/protocol.py", line 111, in __retry
    method(*args)
  File "/home/jasper/anaconda3/lib/python3.9/site-packages/htsget/io.py", line 153, in _handle_http_url
    for piece in self._stream(url, headers):
  File "/home/jasper/anaconda3/lib/python3.9/site-packages/htsget/io.py", line 105, in _stream
    response = self.__get(url, headers=headers, stream=True, timeout=self.timeout)
  File "/home/jasper/anaconda3/lib/python3.9/site-packages/htsget/io.py", line 100, in __get
    raise exceptions.RetryableIOError(he)
htsget.exceptions.RetryableIOError: 500 Server Error:  for url: https://ega.ebi.ac.uk:8052/elixir/data/files/byid/file?accession=EGAF00007243777&format=BAM&chr=chr3
```

**Comment by malloryfreeberg** [comment]
Hi @JasperO98 - Thank you for reporting this issue. It may have occurred while we were experiencing some instability in our underlying infrastructure. This has now been resolved and additionally we worked on and released a new version of both [pyega3 (v5.0.0)](https://pypi.org/project/pyega3/) and the underlying API. Please update to the newest version of pyega3 (you can find the instructions [here](https://github.com/EGA-archive/ega-download-client#installation-and-update)) to enjoy the new features, including a more stable service which results in a higher download success rate.

This GH issue will be closed, but if you continue to experience the same problem, feel free to re-open it. If you experience any other problems, please email the EGA Helpdesk at helpdesk@ega-archive.org and attach the output log produced by pyega3 (pyega3_output.log). The Helpdesk team can then provide further assistance. Thank you!
