### ISSUE TITLE
Error 104: Connection reset by peer

### ISSUE THREAD

**Issue by AnnaK135** [EGA-archive/ega-download-client#177]
**Error 104 Connection reset by peer**

Hello! I am trying to download the datasets with pyega3 using the following command:
```
pyega3 -cf CREDENTIALS_FILE fetch EGADXXXXXXX
```
and I am getting the following error. 
```
(xxx) anna@xxx$ pyega3 -cf CREDENTIALS_FILE fetch EGAD00001002903
[2022-10-24 15:39:06 +0200] 
[2022-10-24 15:39:06 +0200] pyEGA3 - EGA python client version 4.0.0 (https://github.com/EGA-archive/ega-download-client)
[2022-10-24 15:39:06 +0200] Parts of this software are derived from pyEGA (https://github.com/blachlylab/pyega) by James Blachly        
[2022-10-24 15:39:06 +0200] Python version : 3.7.5
[2022-10-24 15:39:06 +0200] OS version : Linux #1 SMP Wed Mar 2 00:30:59 UTC 2022
[2022-10-24 15:39:06 +0200] Server URL: https://ega.ebi.ac.uk:8052/elixir/data
[2022-10-24 15:39:06 +0200] Session-Id: 3272491616
[2022-10-24 15:39:06 +0200] 
[2022-10-24 15:39:06 +0200] Authentication success for user 'xxxxx'
Traceback (most recent call last):
  File "/home/anna/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "/home/anna/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/home/anna/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/home/anna/.local/lib/python3.7/site-packages/urllib3/connection.py", line 426, in connect
    tls_in_tls=tls_in_tls,
  File "/home/anna/.local/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 450, in ssl_wrap_socket
    sock, context, tls_in_tls, server_hostname=server_hostname
  File "/home/anna/.local/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.7/ssl.py", line 423, in wrap_socket
    session=session
  File "/usr/lib/python3.7/ssl.py", line 870, in _create
    self.do_handshake()
  File "/usr/lib/python3.7/ssl.py", line 1139, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/anna/.local/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/anna/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 756, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/anna/.local/lib/python3.7/site-packages/urllib3/util/retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/anna/.local/lib/python3.7/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/home/anna/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "/home/anna/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/home/anna/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/home/anna/.local/lib/python3.7/site-packages/urllib3/connection.py", line 426, in connect
    tls_in_tls=tls_in_tls,
  File "/home/anna/.local/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 450, in ssl_wrap_socket
    sock, context, tls_in_tls, server_hostname=server_hostname
  File "/home/anna/.local/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.7/ssl.py", line 423, in wrap_socket
    session=session
  File "/usr/lib/python3.7/ssl.py", line 870, in _create
    self.do_handshake()
  File "/usr/lib/python3.7/ssl.py", line 1139, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/anna/.local/bin/pyega3", line 11, in <module>
    sys.exit(main())
  File "/home/anna/.local/lib/python3.7/site-packages/pyega3/pyega3.py", line 138, in main
    execute_subcommand(args, data_client)
  File "/home/anna/.local/lib/python3.7/site-packages/pyega3/libs/commands.py", line 22, in execute_subcommand
    fetch_data(args, data_client)
  File "/home/anna/.local/lib/python3.7/site-packages/pyega3/libs/commands.py", line 44, in fetch_data
    args.max_retries, args.retry_wait, args.max_slice_size)
  File "/home/anna/.local/lib/python3.7/site-packages/pyega3/libs/data_set.py", line 76, in download
    authorized_datasets = DataSet.list_authorized_datasets(self.data_client)
  File "/home/anna/.local/lib/python3.7/site-packages/pyega3/libs/data_set.py", line 27, in list_authorized_datasets
    reply = data_client.get_json("/metadata/datasets")
  File "/home/anna/.local/lib/python3.7/site-packages/pyega3/libs/data_client.py", line 30, in get_json
    r = requests.get(url, headers=headers)
  File "/home/anna/.local/lib/python3.7/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/anna/.local/lib/python3.7/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/anna/.local/lib/python3.7/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/anna/.local/lib/python3.7/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/anna/.local/lib/python3.7/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
```
I have used pyega3 with the same credentials and the same machine before (about half a year ago) and it worked fine. 
I have tried updating pyega3, de-installing and installing again, launching pyega in a new conda environment and in another system (Mac) - it all did not work. The issue is continuing for more than a month now. 

Could you, please, help me in resolving the problem?
Thank you in advance!

**Used versions** 
 - Operating System version: *Linux 1 SMP Wed Mar 2 00:30:59 UTC 2022*
 - Python version: *3.7.5*
 - PyEGA3 version: *4.0.0*

**Comment by malloryfreeberg** [comment]
Hi @AnnaK135 - Thank you for reporting this. We have just released a new version of both [pyega3 (v5.0.0)](https://pypi.org/project/pyega3/) and the underlying API. Please update to the newest version of pyega3 (you can find the instructions [here](https://github.com/EGA-archive/ega-download-client#installation-and-update)) to enjoy the new features, including a more stable service which results in a higher download success rate.

I also suggest testing your installation using the test EGA account (instructions [here](https://github.com/EGA-archive/ega-download-client#testing-pyega3-installation)) to determine whether the issue you are experiencing is related to your specific account or not. If updating and testing is successful, and you continue to experience a problem with your account, please email the EGA Helpdesk at helpdesk@ega-archive.org and attach the output log produced by pyega3 (pyega3_output.log). The Helpdesk team can then provide further assistance. Thank you!
