### ISSUE TITLE
connection error

### ISSUE THREAD

**Issue by kac2053** [EGA-archive/ega-download-client#19]
Hi,

I'm not sure if this is an error on ega-download-client, or an error with the computing cluster. In any case, it seems I cannot successfully connect to EGA. I would like to download via the download-client but my back-up plan would be to request EGA for downloading through aspera.

Please let me know what the issue is and what I can do on my end to resolve it. Thanks in advance.

$ python pyega3/pyega3.py -cf CREDENTIALS_FILE -d datasets
EGA python client version 3.0.27
[debugging]
[2018-10-02 18:19:59 -0400] Starting new HTTPS connection (1): ega.ebi.ac.uk:8443
Traceback (most recent call last):
  File "/home/kac2053/miniconda3/envs/ega-download/lib/python3.6/site-packages/urllib3/connection.py", line 171, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/home/kac2053/miniconda3/envs/ega-download/lib/python3.6/site-packages/urllib3/util/connection.py", line 79, in create_connection
    raise err
  File "/home/kac2053/miniconda3/envs/ega-download/lib/python3.6/site-packages/urllib3/util/connection.py", line 69, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kac2053/miniconda3/envs/ega-download/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/kac2053/miniconda3/envs/ega-download/lib/python3.6/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/home/kac2053/miniconda3/envs/ega-download/lib/python3.6/site-packages/urllib3/connectionpool.py", line 849, in _validate_conn
    conn.connect()
  File "/home/kac2053/miniconda3/envs/ega-download/lib/python3.6/site-packages/urllib3/connection.py", line 314, in connect
    conn = self._new_conn()
  File "/home/kac2053/miniconda3/envs/ega-download/lib/python3.6/site-packages/urllib3/connection.py", line 180, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7fde4d998438>: Failed to establish a new connection: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kac2053/miniconda3/envs/ega-download/lib/python3.6/site-packages/requests/adapters.py", line 445, in send
    timeout=timeout
  File "/home/kac2053/miniconda3/envs/ega-download/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/kac2053/miniconda3/envs/ega-download/lib/python3.6/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='ega.ebi.ac.uk', port=8443): Max retries exceeded with url: /ega-openid-connect-server/token (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fde4d998438>: Failed to establish a new connection: [Errno 110] Connection timed out',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pyega3/pyega3.py", line 439, in <module>
    main()
  File "pyega3/pyega3.py", line 415, in main
    token = get_token(credentials)
  File "pyega3/pyega3.py", line 54, in get_token
    r = requests.post( url, headers=headers, data=data )
  File "/home/kac2053/miniconda3/envs/ega-download/lib/python3.6/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/kac2053/miniconda3/envs/ega-download/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/kac2053/miniconda3/envs/ega-download/lib/python3.6/site-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/kac2053/miniconda3/envs/ega-download/lib/python3.6/site-packages/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/home/kac2053/miniconda3/envs/ega-download/lib/python3.6/site-packages/requests/adapters.py", line 513, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='ega.ebi.ac.uk', port=8443): Max retries exceeded with url: /ega-openid-connect-server/token (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fde4d998438>: Failed to establish a new connection: [Errno 110] Connection timed out',))

**Comment by AlexanderSenf** [comment]
There was a database issue on the back end of he API, causing these timeouts. Connectivity has now been restored. 

Please let us know if this issue persists, or returns!

**Comment by kac2053** [comment]
Hi Alex,

I'm still getting the same error. I contacted my university's computing cluster last night - hopefully will hear back from them if it's a problem on our end. 

python pyega3/pyega3.py -cf CREDENTIALS_FILE -d datasets
EGA python client version 3.0.27
[debugging]
[2018-10-03 08:46:34 -0400] Starting new HTTPS connection (1): ega.ebi.ac.uk:8443
Traceback (most recent call last):
  File "/home/kac2053/miniconda3/envs/ega-download/lib/python3.6/site-packages/urllib3/connection.py", line 171, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/home/kac2053/miniconda3/envs/ega-download/lib/python3.6/site-packages/urllib3/util/connection.py", line 79, in create_connection
    raise err
  File "/home/kac2053/miniconda3/envs/ega-download/lib/python3.6/site-packages/urllib3/util/connection.py", line 69, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kac2053/miniconda3/envs/ega-download/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/kac2053/miniconda3/envs/ega-download/lib/python3.6/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/home/kac2053/miniconda3/envs/ega-download/lib/python3.6/site-packages/urllib3/connectionpool.py", line 849, in _validate_conn
    conn.connect()
  File "/home/kac2053/miniconda3/envs/ega-download/lib/python3.6/site-packages/urllib3/connection.py", line 314, in connect
    conn = self._new_conn()
  File "/home/kac2053/miniconda3/envs/ega-download/lib/python3.6/site-packages/urllib3/connection.py", line 180, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7f83ad8974a8>: Failed to establish a new connection: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kac2053/miniconda3/envs/ega-download/lib/python3.6/site-packages/requests/adapters.py", line 445, in send
    timeout=timeout
  File "/home/kac2053/miniconda3/envs/ega-download/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/kac2053/miniconda3/envs/ega-download/lib/python3.6/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='ega.ebi.ac.uk', port=8443): Max retries exceeded with url: /ega-openid-connect-server/token (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f83ad8974a8>: Failed to establish a new connection: [Errno 110] Connection timed out',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pyega3/pyega3.py", line 439, in <module>
    main()
  File "pyega3/pyega3.py", line 415, in main
    token = get_token(credentials)
  File "pyega3/pyega3.py", line 54, in get_token
    r = requests.post( url, headers=headers, data=data )
  File "/home/kac2053/miniconda3/envs/ega-download/lib/python3.6/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/kac2053/miniconda3/envs/ega-download/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/kac2053/miniconda3/envs/ega-download/lib/python3.6/site-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/kac2053/miniconda3/envs/ega-download/lib/python3.6/site-packages/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/home/kac2053/miniconda3/envs/ega-download/lib/python3.6/site-packages/requests/adapters.py", line 513, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='ega.ebi.ac.uk', port=8443): Max retries exceeded with url: /ega-openid-connect-server/token (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f83ad8974a8>: Failed to establish a new connection: [Errno 110] Connection timed out',))
