### ISSUE TITLE
Cannot connect to server 

### ISSUE THREAD

**Issue by clai725** [EGA-archive/ega-download-client#204]
**Unable to connect to server to download dataset**

**I am using a university computing cluster and university storage space to download the dataset I've been granted. After I install pip3 in the computing cluster space I am unable to connect to the server using the command pyega3 -cf CREDENTIALSFILE datasets. My university computing cluster should be able to connect to any server abroad. I work in the States**

Used python3
 - Operating System version: MAC OS Ventura 13.5
 - Python version: 
 - PyEGA3 version: 3.4.1
     

Code after $ pyega3 -cf CREDENTIALSFILE datasets
Traceback (most recent call last):
  File "/home/users/clai725/.local/lib/python3.6/site-packages/requests/adapters.py", line 450, in send
    timeout=timeout
  File "/home/users/clai725/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 799, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/users/clai725/.local/lib/python3.6/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='ega.ebi.ac.uk', port=8052): Max retries exceeded with url: /elixir/data/metadata/datasets (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f7c458fc9b0>: Failed to establish a new connection: [Errno 111] Connection refused',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/users/clai725/.local/bin/pyega3", line 8, in <module>
    sys.exit(main())
  File "/home/users/clai725/.local/lib/python3.6/site-packages/pyega3/pyega3.py", line 647, in main
    reply = api_list_authorized_datasets(token)
  File "/home/users/clai725/.local/lib/python3.6/site-packages/pyega3/pyega3.py", line 162, in api_list_authorized_datasets
    r = requests.get(url, headers=headers)
  File "/home/users/clai725/.local/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/users/clai725/.local/lib/python3.6/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/users/clai725/.local/lib/python3.6/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/users/clai725/.local/lib/python3.6/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/home/users/clai725/.local/lib/python3.6/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='ega.ebi.ac.uk', port=8052): Max retries exceeded with url: /elixir/data/metadata/datasets (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f7c458fc9b0>: Failed to establish a new connection: [Errno 111] Connection refused',)

**Comment by sjparsa** [comment]
I am also experiencing this issue has any solution been found?

**Comment by CsabaHalmagyi** [comment]
Hi @clai725 
Thank you for submitting your error log. I can confirm that we had a connection issue that made downloads slow/not possible. This issue has been fixed now. Could you please retry downloading the dataset?

**Comment by CsabaHalmagyi** [comment]
Hi @clai725,
Thank you for contacting us. You are using an older version of the pyega3 client that is trying to connect to our old data api (which was retired in March this year). If you upgrade the client this issue should be solved. 
Regards,
Csaba

**Comment by clai725** [comment]
How do I upgrade the client?

Sent from my iPhone

On Aug 24, 2023, at 6:28 AM, Csaba Halmagyi ***@***.***> wrote:

﻿

Hi @clai725<https://github.com/clai725>,
Thank you for contacting us. You are using an older version of the pyega3 client that is trying to connect to our old data api (which was retired in March this year). If you upgrade the client this issue should be solved.
Regards,
Csaba

**Comment by clai725** [comment]
pip3 install pyega3==5.0.2

Defaulting to user installation because normal site-packages is not writeable

Collecting pyega3==5.0.2

  Using cached pyega3-5.0.2.tar.gz (42 kB)

  Preparing metadata (setup.py) ... done

Collecting requests==2.26.0

  Using cached requests-2.26.0-py2.py3-none-any.whl (62 kB)

Collecting tqdm==4.19.6

  Using cached tqdm-4.19.6-py2.py3-none-any.whl (52 kB)

Collecting htsget==0.2.5

  Using cached htsget-0.2.5.tar.gz (29 kB)

  Preparing metadata (setup.py) ... error

  ERROR: Command errored out with exit status 1:

   command: /share/software/user/open/python/3.6.1/bin/python3.6 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-8odvahxb/htsget_f5c9dc82faf34574afc64f5bd2df459e/setup.py'"'"'; __file__='"'"'/tmp/pip-install-8odvahxb/htsget_f5c9dc82faf34574afc64f5bd2df459e/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-v0j5hwfn

       cwd: /tmp/pip-install-8odvahxb/htsget_f5c9dc82faf34574afc64f5bd2df459e/

  Complete output (22 lines):

  Traceback (most recent call last):

    File "<string>", line 1, in <module>

    File "/tmp/pip-install-8odvahxb/htsget_f5c9dc82faf34574afc64f5bd2df459e/setup.py", line 43, in <module>

      use_scm_version={"write_to": "htsget/_version.py"},

    File "/share/software/user/open/python/3.6.1/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup

      return distutils.core.setup(**attrs)

    File "/share/software/user/open/python/3.6.1/lib/python3.6/distutils/core.py", line 108, in setup

      _setup_distribution = dist = klass(attrs)

    File "/share/software/user/open/python/3.6.1/lib/python3.6/site-packages/setuptools/dist.py", line 370, in __init__

      k: v for k, v in attrs.items()

    File "/share/software/user/open/python/3.6.1/lib/python3.6/distutils/dist.py", line 281, in __init__

      self.finalize_options()

    File "/share/software/user/open/python/3.6.1/lib/python3.6/site-packages/setuptools/dist.py", line 529, in finalize_options

      ep.load()(self, ep.name, value)

    File "/share/software/user/open/python/3.6.1/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2318, in load

      return self.resolve()

    File "/share/software/user/open/python/3.6.1/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2324, in resolve

      module = __import__(self.module_name, fromlist=['__name__'], level=0)

    File "/tmp/pip-install-8odvahxb/htsget_f5c9dc82faf34574afc64f5bd2df459e/.eggs/setuptools_scm-7.1.0-py3.6.egg/setuptools_scm/__init__.py", line 5

      from __future__ import annotations

      ^

  SyntaxError: future feature annotations is not defined

  ----------------------------------------

WARNING: Discarding https://files.pythonhosted.org/packages/99/23/dedd2de16464cff36870019c7894cdbae83f121ab479121ababbef2add48/htsget-0.2.5.tar.gz#sha256=d383dc36f699bd921f760f5500c8ed251e5f8358a7cc219c6c89c35d103e8045 (from https://pypi.org/simple/htsget/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

ERROR: Could not find a version that satisfies the requirement htsget==0.2.5 (from pyega3) (from versions: 0.1.0a1, 0.1.0a2, 0.1.0a3, 0.1.0a4, 0.1.0a5, 0.1.0, 0.1.1, 0.1.2, 0.2.0, 0.2.1, 0.2.2, 0.2.3, 0.2.4, 0.2.5, 0.2.6)

ERROR: No matching distribution found for htsget==0.2.5

________________________________
