### ISSUE TITLE
Download not working even with test data

### ISSUE THREAD

**Issue by mukamel-lab** [EGA-archive/ega-download-client#207]
I just installed pyEGA3 and am not able to successfully download data. Error log is below. Any help would be welcome - thanks!

(base) Erans-Space-Gray-Mac:~ emukamel$ pyega3 -t fetch EGAF00007243783
[2023-09-17 13:19:16 -0700] 
[2023-09-17 13:19:16 -0700] pyEGA3 - EGA python client version 5.0.2 (https://github.com/EGA-archive/ega-download-client)
[2023-09-17 13:19:16 -0700] Parts of this software are derived from pyEGA (https://github.com/blachlylab/pyega) by James Blachly
[2023-09-17 13:19:16 -0700] Python version : 3.9.12
[2023-09-17 13:19:16 -0700] OS version : Darwin Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:22 PDT 2023; root:xnu-8796.121.3~7/RELEASE_X86_64
[2023-09-17 13:19:16 -0700] MacOS version : 10.16
[2023-09-17 13:19:17 -0700] Server URL: https://ega.ebi.ac.uk:8443/v2
[2023-09-17 13:19:17 -0700] Session-Id: 2695362527
[2023-09-17 13:19:19 -0700] 
[2023-09-17 13:19:19 -0700] Authentication success for user 'ega-test-data@ebi.ac.uk'
[2023-09-17 13:19:20 -0700] File Id: 'EGAF00007243783'(83 bytes).
[2023-09-17 13:19:20 -0700] Total space : 465.63 GiB
[2023-09-17 13:19:20 -0700] Used space : 385.05 GiB
[2023-09-17 13:19:20 -0700] Free space : 80.57 GiB
[2023-09-17 13:19:20 -0700] Download starting [using 1 connection(s), file size 67 and chunk length 104857600]...
  0%|                                                                                                        | 0.00/67.0 [00:00<?, ?B/s]
[2023-09-17 13:25:58 -0700] HTTPSConnectionPool(host='ega.ebi.ac.uk', port=8443): Max retries exceeded with url: /v2/files/EGAF00007243783?destinationFormat=plain (Caused by ResponseError('too many 503 error responses'))
Traceback (most recent call last):
  File "/Users/emukamel/opt/anaconda3/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/Users/emukamel/opt/anaconda3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 846, in urlopen
    return self.urlopen(
  File "/Users/emukamel/opt/anaconda3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 846, in urlopen
    return self.urlopen(
  File "/Users/emukamel/opt/anaconda3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 846, in urlopen
    return self.urlopen(
  [Previous line repeated 7 more times]
  File "/Users/emukamel/opt/anaconda3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 836, in urlopen
    retries = retries.increment(method, url, response=response, _pool=self)
  File "/Users/emukamel/opt/anaconda3/lib/python3.9/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='ega.ebi.ac.uk', port=8443): Max retries exceeded with url: /v2/files/EGAF00007243783?destinationFormat=plain (Caused by ResponseError('too many 503 error responses'))

**Comment by mukamel-lab** [comment]
As of this morning the download using pyega3 is working for me.
