### ISSUE TITLE
Warning: Unknown argument(s): {'unit_divisor': 1024}

### ISSUE THREAD

**Issue by petrsha** [EGA-archive/ega-download-client#22]
Hi,
I'm getting the following when trying to download a file (same for a whole dataset) from the EGA:

[2018-10-16 20:49:47 +0200] File Id: 'EGAF00000865484'(5768819038 bytes).
[2018-10-16 20:49:47 +0200] Download starting [using 1 connection(s)]...
[2018-10-16 20:49:47 +0200] Unknown argument(s): {'unit_divisor': 1024}
[2018-10-16 20:49:52 +0200] retry attempt 1
[2018-10-16 20:49:52 +0200] Download starting [using 1 connection(s)]...
[2018-10-16 20:49:52 +0200] Unknown argument(s): {'unit_divisor': 1024}
[2018-10-16 20:49:57 +0200] retry attempt 2
[2018-10-16 20:49:57 +0200] Download starting [using 1 connection(s)]...
[2018-10-16 20:49:57 +0200] Unknown argument(s): {'unit_divisor': 1024}
[2018-10-16 20:50:02 +0200] retry attempt 3
[2018-10-16 20:50:02 +0200] Download starting [using 1 connection(s)]...
[2018-10-16 20:50:02 +0200] Unknown argument(s): {'unit_divisor': 1024}
Traceback (most recent call last):
File "pyega3/pyega3.py", line 439, in 
main()
File "pyega3/pyega3.py", line 433, in main
download_file_retry( token, args.identifier, file_name, file_size, check_sum, args.connections, key, args.saveto, genomic_range_args )
File "pyega3/pyega3.py", line 333, in download_file_retry
raise e
File "pyega3/pyega3.py", line 328, in download_file_retry
download_file(token, file_id, file_size, check_sum, num_connections, key, output_file)
File "pyega3/pyega3.py", line 274, in download_file
with tqdm(total=int(file_size), unit='B', unit_scale=True, unit_divisor=1024) as pbar:
File "/opt/install/dir/anaconda/envs/ICGC/lib/python3.6/site-packages/tqdm-4.7.2-py3.6.egg/tqdm/_tqdm.py", line 427, in init
Warning: Unknown argument(s): {'unit_divisor': 1024}

**Comment by jblachly** [comment]
@petrsha I notice you opened the same issue in my pyega client: https://github.com/blachlylab/pyega/issues/1

It looks like an issue with the tqdm package.

Note that my package is pyega, which it appears EGA's pyega3 is based upon.
