### ISSUE TITLE
Invalid username, password or secret key - please check and retry

### ISSUE THREAD

**Issue by SuhasSrinivasan** [EGA-archive/ega-download-client#228]
Dear EGA Team,

Thank you for developing and maintaining these services and tools.

I have been experiencing authentication issues for the past two weeks and have not found a workaround.
I have tried many troubleshooting steps, none of which helped.
I submitted a ticket, but the response I received does not match observed behavior for test dataset.
I wanted to reopen issue #162, but as there was no option, creating this issue.

### Response received for ticket 750276
```
Dear user,

We wanted to inform you that PyEGA3 is currently experiencing server errors
due to high traffic. As a result, it is not possible to answer all requests,
leading to 400, 500 and 503 errors.

To mitigate this issue, we kindly request users to retry their downloads
multiple times and at different times, downloading the files individually if
necessary. The response may vary depending on the traffic the client is
experiencing at that moment. We are aware that this is not the most convenient
solution, but please be assured that our developers are actively working on a
fix for this problem.

If the issue persists for a week, please create a new ticket and share the log
file created in the folder where PyEGA3 is running.

Thank you for your understanding and patience.

Kind regards,

EGA Helpdesk Team.
```

### Authentication error (suspected server traffic by Help Desk)
```
pyega3 -cf ./ega_cred.json datasets
[2024-07-06 12:03:23 -0700]
[2024-07-06 12:03:23 -0700] pyEGA3 - EGA python client version 5.2.0 (https://github.com/EGA-archive/ega-download-client)
[2024-07-06 12:03:23 -0700] Parts of this software are derived from pyEGA (https://github.com/blachlylab/pyega) by James Blachly
[2024-07-06 12:03:23 -0700] Python version : 3.11.4
[2024-07-06 12:03:23 -0700] OS version : Darwin Darwin Kernel Version 23.5.0: Wed May  1 20:09:52 PDT 2024; root:xnu-10063.121.3~5/RELEASE_X86_64
[2024-07-06 12:03:23 -0700] MacOS version : 10.16
[2024-07-06 12:03:23 -0700] Server URL: https://ega.ebi.ac.uk:8443/v2
[2024-07-06 12:03:23 -0700] Session-Id: 1840138742
[2024-07-06 12:03:29 -0700]
[2024-07-06 12:03:29 -0700] Invalid username, password or secret key - please check and retry. If problem persists contact helpdesk on helpdesk@ega-archive.org
Traceback (most recent call last):
  File "/Users/suhas/miniconda3/lib/python3.11/site-packages/pyega3/libs/auth_client.py", line 39, in token
    r.raise_for_status()
  File "/Users/suhas/miniconda3/lib/python3.11/site-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error:  for url: https://ega.ebi.ac.uk:8443/ega-openid-connect-server/token
```

### Querying test dataset (no server traffic issue)
```
pyega3 -d -t datasets
[2024-07-06 11:49:07 -0700]
[2024-07-06 11:49:07 -0700] pyEGA3 - EGA python client version 5.2.0 (https://github.com/EGA-archive/ega-download-client)
[2024-07-06 11:49:07 -0700] Parts of this software are derived from pyEGA (https://github.com/blachlylab/pyega) by James Blachly
[2024-07-06 11:49:07 -0700] Python version : 3.11.4
[2024-07-06 11:49:07 -0700] OS version : Darwin Darwin Kernel Version 23.5.0: Wed May  1 20:09:52 PDT 2024; root:xnu-10063.121.3~5/RELEASE_X86_64
[2024-07-06 11:49:07 -0700] MacOS version : 10.16
[2024-07-06 11:49:07 -0700] Server URL: https://ega.ebi.ac.uk:8443/v2
[2024-07-06 11:49:07 -0700] Session-Id: 364721108
[2024-07-06 11:49:07 -0700] Starting new HTTPS connection (1): ipinfo.io:443
[2024-07-06 11:49:07 -0700] https://ipinfo.io:443 "GET /json HTTP/1.1" 200 334
[2024-07-06 11:49:07 -0700] Starting new HTTPS connection (1): ega.ebi.ac.uk:8443
[2024-07-06 11:49:15 -0700] https://ega.ebi.ac.uk:8443 "POST /ega-openid-connect-server/token HTTP/1.1" 200 None
[2024-07-06 11:49:15 -0700]
[2024-07-06 11:49:15 -0700] Authentication success for user 'ega-test-data@ebi.ac.uk'
[2024-07-06 11:49:15 -0700] Starting new HTTPS connection (1): ega.ebi.ac.uk:8443
[2024-07-06 11:49:25 -0700] https://ega.ebi.ac.uk:8443 "GET /v2/metadata/datasets HTTP/1.1" 200 None
[2024-07-06 11:49:25 -0700] Request URL : https://ega.ebi.ac.uk:8443/v2/metadata/datasets
[2024-07-06 11:49:25 -0700] Response    :
 [
    {
        "datasetId": "EGAD00001003338",
        "description": "GA4GH data stream test dataset",
        "dacStableId": "EGAC00001000514"
    },
    {
        "datasetId": "EGAD00001008392",
        "description": "Rare Disease Synthetic Dataset",
        "dacStableId": "EGAC00001000514"
    },
    {
        "datasetId": "EGAD00001009826",
        "description": "Test dataset with ligh-weight files",
        "dacStableId": "EGAC00001000514"
    },
    {
        "datasetId": "EGAD00001006673",
        "description": "CINECA Synthetic Dataset referencing fake samples",
        "dacStableId": "EGAC00001000514"
    }
]
[2024-07-06 11:49:25 -0700] Dataset ID
[2024-07-06 11:49:25 -0700] -----------------
[2024-07-06 11:49:25 -0700] EGAD00001003338
[2024-07-06 11:49:25 -0700] EGAD00001008392
[2024-07-06 11:49:25 -0700] EGAD00001009826
[2024-07-06 11:49:25 -0700] EGAD00001006673
```

### Attempted troubleshooting steps
1. Reset EGA password and signed out all sessions
2. **pyEGA3** credentials JSON file, tried both username and email address values to see if either would work.
3. With Crypt4GH public key saved to EGA profile, attempted Live Outbox with **FileZilla** (both username and email).
`The file could not be loaded or does not contain a private key.`.
4. With Crypt4GH public key saved to EGA profile, attempted **sftp** from CLI (both username and email). 
`connect to host outbox.ega-archive.org port 22: Connection refused`
5. Tried password authentication with **FileZilla** (both username and email).
`Error:         	Connection timed out after 20 seconds of inactivity`
`Error:         	Could not connect to server`
----

Any help with this issue would be greatly appreciated

**Comment by CsabaHalmagyi** [comment]
Dear @SuhasSrinivasan 
Thank you for contacting us. Your investigation clearly highlighted that the pyega3 client can authenticate the user upon providing the correct username and password (you successfully authenticated when using the test account and password). 
It seems that there is a problem with the password you have for your personal account.  
Please contact  EGA Helpdesk directly at [helpdesk@ega-archive.org](mailto:helpdesk@ega-archive.org) and tell them that you reset your password on the website but you can't authenticate with the pyega3 client. They should be able to fix this problem.
Closing this issue, as it is not for the attention of the development team.

**Comment by SuhasSrinivasan** [comment]
For completeness, posting here the technical resolution from the Help Desk team.
After the below change, I was able to successfully query the authorized datasets for my account.

```
Thank you for your response. Yesterday we made adjustments to our permissions
synchronisation services. Please confirm if your problem persists as of today.
```

**Comment by eightYao2** [comment]
@CsabaHalmagyi 

Dear EGA Team,

We are also experiencing this issue. I have attempted various troubleshooting steps, but none have resolved the problem. I have sent an email to the helpdesk and hope that you can grant us Aspera access.

Looking forward to your support.Thank you.
