### ISSUE TITLE
failed to download the files

### ISSUE THREAD

**Issue by alkurowska** [EGA-archive/ega-download-client#229]
I am trying to download specific files from a dataset. But it's unsuccessful. It seems to me that there is some general error, as the code for the test dataset does not work either. I am using version 3.4.1.

`pyega3 -d -t datasets
[2024-07-14 16:22:42 +0300] 
[2024-07-14 16:22:42 +0300] pyEGA3 - EGA python client version 3.4.1 (https://github.com/EGA-archive/ega-download-client)
[2024-07-14 16:22:42 +0300] Parts of this software are derived from pyEGA (https://github.com/blachlylab/pyega) by James Blachly
[2024-07-14 16:22:42 +0300] Python version : 3.9.5
[2024-07-14 16:22:42 +0300] OS version : Linux #1 SMP PREEMPT_DYNAMIC Tue Apr 11 19:09:37 UTC 2023
[2024-07-14 16:22:42 +0300] Server URL: https://ega.ebi.ac.uk:8052/elixir/data
[2024-07-14 16:22:42 +0300] Session-Id: 753511105
[2024-07-14 16:22:42 +0300] Starting new HTTPS connection (1): ega.ebi.ac.uk:8443
[2024-07-14 16:22:43 +0300] https://ega.ebi.ac.uk:8443 "POST /ega-openid-connect-server/token HTTP/1.1" 200 None
[2024-07-14 16:22:43 +0300] 
[2024-07-14 16:22:43 +0300] Authentication success for user 'ega-test-data@ebi.ac.uk'
[2024-07-14 16:22:43 +0300] Starting new HTTPS connection (1): ega.ebi.ac.uk:8052
Traceback (most recent call last):
  File "/ibex/sw/csi/pyega3/3.4.1/el7.9_python3/miniconda3/lib/python3.9/site-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/ibex/sw/csi/pyega3/3.4.1/el7.9_python3/miniconda3/lib/python3.9/site-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/ibex/sw/csi/pyega3/3.4.1/el7.9_python3/miniconda3/lib/python3.9/site-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/ibex/sw/csi/pyega3/3.4.1/el7.9_python3/miniconda3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/ibex/sw/csi/pyega3/3.4.1/el7.9_python3/miniconda3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/ibex/sw/csi/pyega3/3.4.1/el7.9_python3/miniconda3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/ibex/sw/csi/pyega3/3.4.1/el7.9_python3/miniconda3/lib/python3.9/site-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()
  File "/ibex/sw/csi/pyega3/3.4.1/el7.9_python3/miniconda3/lib/python3.9/site-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x14aaee6d7820>: Failed to establish a new connection: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/ibex/sw/csi/pyega3/3.4.1/el7.9_python3/miniconda3/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/ibex/sw/csi/pyega3/3.4.1/el7.9_python3/miniconda3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/ibex/sw/csi/pyega3/3.4.1/el7.9_python3/miniconda3/lib/python3.9/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='ega.ebi.ac.uk', port=8052): Max retries exceeded with url: /elixir/data/metadata/datasets (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x14aaee6d7820>: Failed to establish a new connection: [Errno 110] Connection timed out'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/ibex/sw/csi/pyega3/3.4.1/el7.9_python3/miniconda3/bin/pyega3", line 8, in <module>
    sys.exit(main())
  File "/ibex/sw/csi/pyega3/3.4.1/el7.9_python3/miniconda3/lib/python3.9/site-packages/pyega3/pyega3.py", line 647, in main
    reply = api_list_authorized_datasets(token)
  File "/ibex/sw/csi/pyega3/3.4.1/el7.9_python3/miniconda3/lib/python3.9/site-packages/pyega3/pyega3.py", line 162, in api_list_authorized_datasets
    r = requests.get(url, headers=headers)
  File "/ibex/sw/csi/pyega3/3.4.1/el7.9_python3/miniconda3/lib/python3.9/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/ibex/sw/csi/pyega3/3.4.1/el7.9_python3/miniconda3/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/ibex/sw/csi/pyega3/3.4.1/el7.9_python3/miniconda3/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/ibex/sw/csi/pyega3/3.4.1/el7.9_python3/miniconda3/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/ibex/sw/csi/pyega3/3.4.1/el7.9_python3/miniconda3/lib/python3.9/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='ega.ebi.ac.uk', port=8052): Max retries exceeded with url: /elixir/data/metadata/datasets (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x14aaee6d7820>: Failed to establish a new connection: [Errno 110] Connection timed out'))`

**Comment by CsabaHalmagyi** [comment]
Hi @alkurowska 
You are using a very old version of the client that is using an API that was retired last year. Please upgrade your client to enjoy the benefit of the new API.
