### ISSUE TITLE
Timeout connection error

### ISSUE THREAD

**Issue by Jordanwconway** [EGA-archive/ega-download-client#236]
Dear PyEGA team

I am trying to download datasets from EGA from Australia. I have tested in order to display the EGA datasets we have access to but even this is causing the below connection timeout error. I tried also just displaying one of the test data sets and I get the same error. I was wondering if you had any advice on this error and why it may not be successfully establishing a connection so that I can proceed with downloading the datasets.  Kind regards, Jordan 

[2024-08-02 14:29:02 +1000] 
[2024-08-02 14:29:02 +1000] pyEGA3 - EGA python client version 3.4.1 (https://github.com/EGA-archive/ega-download-client)
[2024-08-02 14:29:02 +1000] Parts of this software are derived from pyEGA (https://github.com/blachlylab/pyega) by James Blachly
[2024-08-02 14:29:02 +1000] Python version : 3.6.9
[2024-08-02 14:29:02 +1000] OS version : Linux #202001230832 SMP Thu Jan 23 08:34:56 UTC 2020
[2024-08-02 14:29:02 +1000] Server URL: https://ega.ebi.ac.uk:8052/elixir/data
[2024-08-02 14:29:02 +1000] Session-Id: 3758495892
[2024-08-02 14:29:04 +1000] 
[2024-08-02 14:29:04 +1000] Authentication success for user 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 144, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 83, in create_connection
    raise err
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 852, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 298, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 153, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7f3f20d3f278>: Failed to establish a new connection: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='ega.ebi.ac.uk', port=8052): Max retries exceeded with url: /elixir/data/metadata/datasets (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f3f20d3f278>: Failed to establish a new connection: [Errno 110] Connection timed out',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/pyega3", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/pyega3/pyega3.py", line 647, in main
    reply = api_list_authorized_datasets(token)
  File "/usr/local/lib/python3.6/dist-packages/pyega3/pyega3.py", line 162, in api_list_authorized_datasets
    r = requests.get(url, headers=headers)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 520, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 630, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='ega.ebi.ac.uk', port=8052): Max retries exceeded with url: /elixir/data/metadata/datasets (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f3f20d3f278>: Failed to establish a new connection: [Errno 110] Connection timed out',))

**Comment by CsabaHalmagyi** [comment]
Dear @Jordanwconway 
You are using a very old version of the pyega client (3.4.1) that relies on an API endpoint that was retired. Please upgrade your pyega client to have access its updated features.
Closing this issue.
