### ISSUE TITLE
Unable to login to account with two-factor authentication (OTP)

### ISSUE THREAD

**Issue by wna-se** [EGA-archive/ega-download-client#239]
**Unable to login to account with two-factor authentication (OTP) **

When running `pyega3 datasets` and providing valid EGA credentials I get the following error message:

**Used versions** 
 - Operating System version: Ubuntu 22.04.4 LTS (containerized)
 - Python version: Python 3.11.9
 - PyEGA3 version: pyEGA3 - EGA python client version 5.2.0 

**To Reproduce**

Activate two-factor authentication on the account and try to use the client. 

**Observed behaviour**

Asked for username and password followed by an error about `Invalid username, password or secret key`

**Expected behaviour**

Being asked to provide OTP code in addition to password.

**Screenshots and error messages**

```
Invalid username, password or secret key - please check and retry. If problem persists contact helpdesk on helpdesk@ega-archive.org
Traceback (most recent call last):
  File "/opt/conda/lib/python3.11/site-packages/pyega3/libs/auth_client.py", line 39, in token
    r.raise_for_status()
  File "/opt/conda/lib/python3.11/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error:  for url: https://ega.ebi.ac.uk:8443/ega-openid-connect-server/token
```

**Additional context**

Looking at [auth_client.py#L28](https://github.com/EGA-archive/ega-download-client/blob/a90574e252b0d0d0a49673a00045d1d29542ce37/pyega3/libs/auth_client.py#L28) the required `otp` field seems to be missing. E.g., the function has not been implemented.

**Comment by DexinYang1998** [comment]
We have encountered the same issue since last month.

**Comment by CsabaHalmagyi** [comment]
OTP is currently not supported by the python client. Closing.
