### ISSUE TITLE
HTTPSConnectionPool Error

### ISSUE THREAD

**Issue by hannanw** [EGA-archive/ega-download-client#240]
Hi,

I am trying to download some files via this tool, but am facing some connection error. I have updated to the latest version of pyega3 

```
> $ pyega3 --version
> [2024-09-03 11:58:41 +0800] 
> [2024-09-03 11:58:41 +0800] pyEGA3 - EGA python client version 5.2.0 (https://github.com/EGA-archive/ega-download-client)
```

This is the error I am facing

```
$ pyega3 -cf EGA_config.json files EGAD00001001334
[2024-09-03 12:12:53 +0800] 
[2024-09-03 12:12:53 +0800] pyEGA3 - EGA python client version 5.2.0 (https://github.com/EGA-archive/ega-download-client)
[2024-09-03 12:12:53 +0800] Parts of this software are derived from pyEGA (https://github.com/blachlylab/pyega) by James Blachly
[2024-09-03 12:12:53 +0800] Python version : 3.9.18
[2024-09-03 12:12:53 +0800] OS version : Linux #24-Ubuntu SMP Wed May 16 12:15:17 UTC 2018
[2024-09-03 12:12:53 +0800] Server URL: https://ega.ebi.ac.uk:8443/v2
[2024-09-03 12:12:53 +0800] Session-Id: 2391086502
[2024-09-03 12:12:57 +0800] 
[2024-09-03 12:12:57 +0800] Authentication success for user 'e0004488@u.nus.edu'
Traceback (most recent call last):
  File "/home/hannan/anaconda3/envs/EGA_download/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/home/hannan/anaconda3/envs/EGA_download/lib/python3.9/site-packages/urllib3/connectionpool.py", line 846, in urlopen
    return self.urlopen(
  File "/home/hannan/anaconda3/envs/EGA_download/lib/python3.9/site-packages/urllib3/connectionpool.py", line 846, in urlopen
    return self.urlopen(
  File "/home/hannan/anaconda3/envs/EGA_download/lib/python3.9/site-packages/urllib3/connectionpool.py", line 846, in urlopen
    return self.urlopen(
  [Previous line repeated 7 more times]
  File "/home/hannan/anaconda3/envs/EGA_download/lib/python3.9/site-packages/urllib3/connectionpool.py", line 836, in urlopen
    retries = retries.increment(method, url, response=response, _pool=self)
  File "/home/hannan/anaconda3/envs/EGA_download/lib/python3.9/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='ega.ebi.ac.uk', port=8443): Max retries exceeded with url: /v2/metadata/datasets (Caused by ResponseError('too many 500 error responses'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hannan/anaconda3/envs/EGA_download/bin/pyega3", line 8, in <module>
    sys.exit(main())
  File "/home/hannan/anaconda3/envs/EGA_download/lib/python3.9/site-packages/pyega3/pyega3.py", line 153, in main
    execute_subcommand(args, data_client)
  File "/home/hannan/anaconda3/envs/EGA_download/lib/python3.9/site-packages/pyega3/libs/commands.py", line 19, in execute_subcommand
    list_files_in_dataset(args, data_client)
  File "/home/hannan/anaconda3/envs/EGA_download/lib/python3.9/site-packages/pyega3/libs/commands.py", line 68, in list_files_in_dataset
    files = dataset.list_files()
  File "/home/hannan/anaconda3/envs/EGA_download/lib/python3.9/site-packages/pyega3/libs/data_set.py", line 46, in list_files
    authorized_datasets = DataSet.list_authorized_datasets(self.data_client)
  File "/home/hannan/anaconda3/envs/EGA_download/lib/python3.9/site-packages/pyega3/libs/data_set.py", line 27, in list_authorized_datasets
    reply = data_client.get_json("/datasets")
  File "/home/hannan/anaconda3/envs/EGA_download/lib/python3.9/site-packages/pyega3/libs/data_client.py", line 61, in get_json
    r = self.session.get(url, headers=headers)
  File "/home/hannan/anaconda3/envs/EGA_download/lib/python3.9/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/home/hannan/anaconda3/envs/EGA_download/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/hannan/anaconda3/envs/EGA_download/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/hannan/anaconda3/envs/EGA_download/lib/python3.9/site-packages/requests/adapters.py", line 507, in send
    raise RetryError(e, request=request)
requests.exceptions.RetryError: HTTPSConnectionPool(host='ega.ebi.ac.uk', port=8443): Max retries exceeded with url: /v2/metadata/datasets (Caused by ResponseError('too many 500 error responses'))
```

Any help/advice would be greatly appreciated, thanks!

**Comment by hyjforesight** [comment]
same error

**Comment by ghost** [comment]
Hi I have the exact same error, did you manage to debug it?

**Comment by hlwCoBi** [comment]
Hi! I have the same error, could you solve it?
