### ISSUE TITLE
dropped connection: ega.ebi.ac.uk

### ISSUE THREAD

**Issue by Yousuk-Song** [EGA-archive/ega-download-client#243]
[2024-09-24 14:45:16 +0900] Slice error: received=133169152, requested=1073741824, file='/mnt/S1/data/rawdata/scRSEQ_AML/EGAF00005284760/.tmp_download/EGAF00005284760-from-0-len-1073741824.slice.tmp'
Traceback (most recent call last):
  File "/home/jmchoi/.local/lib/python3.10/site-packages/pyega3/libs/data_file.py", line 346, in _download_whole_file
    self.download_file(output_file, num_connections, max_slice_size)
  File "/home/jmchoi/.local/lib/python3.10/site-packages/pyega3/libs/data_file.py", line 162, in download_file
    for part_file_name in executor.map(self.download_file_slice_, params):
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 621, in result_iterator
    yield _result_or_cancel(fs.pop())
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 319, in _result_or_cancel
    return fut.result(timeout)
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/jmchoi/.local/lib/python3.10/site-packages/pyega3/libs/data_file.py", line 196, in download_file_slice_
    return self.download_file_slice(*args)
  File "/home/jmchoi/.local/lib/python3.10/site-packages/pyega3/libs/data_file.py", line 238, in download_file_slice
    raise SliceError(f"Slice error: received={total_received}, requested={length}, file='{file_name}'")
pyega3.libs.error.SliceError: Slice error: received=133169152, requested=1073741824, file='/mnt/S1/data/rawdata/scRSEQ_AML/EGAF00005284760/.tmp_download/EGAF00005284760-from-0-len-1073741824.slice.tmp'
[2024-09-24 14:45:16 +0900] Resetting dropped connection: ega.ebi.ac.uk
[2024-09-24 14:45:24 +0900] https://ega.ebi.ac.uk:8443 "POST /v2/download-stats HTTP/1.1" 200 None

I'm trying to download 22GB files and the downloading keeps resetting after getting 9-10% and this is killing me.

How can I deal with this issue?

**Comment by hyjforesight** [comment]
I met the same error recently. But it worked well before. I guessed it might be the problem of the server.
