### ISSUE TITLE
pyega3.libs.error.SliceError: Slice error ; Error in data Downloading.

### ISSUE THREAD

**Issue by BiodeB** [EGA-archive/ega-download-client#244]
**pyega3.libs.error.SliceError: Slice error**

Hi,
This is first time I'm using this software.
The following problem occurred when I attempted to download the EGAF00000280195.bam file (~107 GB). I also tried running the command with the -c 5 to 15 and 30 options, but to no improvement.
Hoping for best advice to overcome this issue.

```
cat pyega3_output.log
[2024-09-25 13:21:32 -0400] 
[2024-09-25 13:21:32 -0400] pyEGA3 - EGA python client version 5.2.0 (https://github.com/EGA-archive/ega-download-client)
[2024-09-25 13:21:32 -0400] Parts of this software are derived from pyEGA (https://github.com/blachlylab/pyega) by James Blachly
[2024-09-25 13:21:32 -0400] Python version : 3.12.6
[2024-09-25 13:21:32 -0400] OS version : Linux #1 SMP Wed Apr 24 16:01:50 UTC 2024
[2024-09-25 13:21:32 -0400] Server URL: https://ega.ebi.ac.uk:8443/v2
[2024-09-25 13:21:32 -0400] Session-Id: 2831686207
[2024-09-25 13:21:33 -0400] 
[2024-09-25 13:21:33 -0400] Authentication success for user 'eja78@rwjms.rutgers.edu'
[2024-09-25 13:21:34 -0400] File Id: 'EGAF00000280195'(106330786408 bytes).
[2024-09-25 13:21:34 -0400] Total space : 2867466.00 GiB
[2024-09-25 13:21:34 -0400] Used space : 2376991.87 GiB
[2024-09-25 13:21:34 -0400] Free space : 490474.13 GiB
[2024-09-25 13:21:34 -0400] Download starting [using 5 connection(s), file size 106330786392 and chunk length 104857600]...
[2024-09-25 13:21:38 -0400] Slice error: received=0, requested=104857600, file='/projects/foran/SDLab/DK/EACM_work/FWORK/Data/EGAF00000280195/.tmp_download/EGAF00000280195-from-0-len-104857600.slice.tmp'
Traceback (most recent call last):
  File "/home/dk1187/.conda/envs/pyega3_env/lib/python3.12/site-packages/pyega3/libs/data_file.py", line 346, in _download_whole_file
    self.download_file(output_file, num_connections, max_slice_size)
  File "/home/dk1187/.conda/envs/pyega3_env/lib/python3.12/site-packages/pyega3/libs/data_file.py", line 162, in download_file
    for part_file_name in executor.map(self.download_file_slice_, params):
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dk1187/.conda/envs/pyega3_env/lib/python3.12/concurrent/futures/_base.py", line 619, in result_iterator
    yield _result_or_cancel(fs.pop())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dk1187/.conda/envs/pyega3_env/lib/python3.12/concurrent/futures/_base.py", line 317, in _result_or_cancel
    return fut.result(timeout)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/dk1187/.conda/envs/pyega3_env/lib/python3.12/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/dk1187/.conda/envs/pyega3_env/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/home/dk1187/.conda/envs/pyega3_env/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dk1187/.conda/envs/pyega3_env/lib/python3.12/site-packages/pyega3/libs/data_file.py", line 196, in download_file_slice_
    return self.download_file_slice(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dk1187/.conda/envs/pyega3_env/lib/python3.12/site-packages/pyega3/libs/data_file.py", line 238, in download_file_slice
    raise SliceError(f"Slice error: received={total_received}, requested={length}, file='{file_name}'")
pyega3.libs.error.SliceError: Slice error: received=0, requested=104857600, file='/projects/foran/SDLab/DK/EACM_work/FWORK/Data/EGAF00000280195/.tmp_download/EGAF00000280195-from-0-len-104857600.slice.tmp'
```

 - Python version: 
 - *(e.g `Python 3.12.6`)*
 - PyEGA3 version: (e.g `European Genome-phenome Archive. Client version: 5.2.0`)*
     PyEGA3 was installed using conda

```
 pyega3 -help
usage: pyega3 [-h] [-d] [-cf CONFIG_FILE] [-sf SERVER_FILE] [-c CONNECTIONS] [-t] [-ms MAX_SLICE_SIZE] [-j] [-v] {datasets,files,fetch} ...

Download from the European Genome-phenome Archive. Client version: 5.2.0

positional arguments:
  {datasets,files,fetch}
                        subcommands
    datasets            List authorized datasets
    files               List files in a specified dataset
    fetch               Fetch a dataset or file
```

**To Reproduce**
*e.g.:*
1. Trying to download BAM file `EGAF00000280195`.
```
time  pyega3 -c 5 -cf $WorkDir/CREDENTIALS_FILE.json fetch EGAF00000280195  --retry-wait 3600  --output-dir $WorkDir/Data

```

**Comment by hyjforesight** [comment]
I met the same error recently. But it worked well before.

**Comment by kunstner** [comment]
I'm facing the same error.

**Comment by songlyzz** [comment]
me too

**Comment by CsabaHalmagyi** [comment]
Dear @BiodeB 
Could you please confirm the issue still persist?

**Comment by kunstner** [comment]
Hi @CsabaHalmagyi 

I can confirm that the issue is still occurring.

Best

**Comment by sangmi9618** [comment]
Hi @CsabaHalmagyi ,
I also encountered the same issue while downloading multiple BAM files using pyega3.
I've recently heard from EGA helpdesk team that now pyega3 is working properly but the issue like below still occurred:
`pyega3.libs.error.SliceError: Slice error: received=503307916, requested=1073741824, file='/EGAD00001011186/EGAF00008177317/.tmp_download/EGAF00008177317-from-38654705664-len-1073741824.slice.tmp`

Could you provide any workarounds for this issue?

Best,
Sandra

**Comment by KonstantinaChe** [comment]
I am having the same issue. Could we get some help perhaps? Or at least an explanation why this happens?

**Comment by jenny8030** [comment]
I met the same issue.

**Comment by jo-mc** [comment]
I seemed to have same error, modded data_files.py and it is working. 

[data_file.py](https://github.com/user-attachments/files/26990020/data_file.py)

Patch to data_file

1. Adds file_size to the params tuple so each slice knows the total file size
2. Relaxes the merge condition to use actual received bytes instead of == file_size
3. Adds file_size=None parameter to download_file_slice() signature
4. Replaces strict SliceError with last-slice awareness — mid-file short reads still raise and retry, only the last slice accepts a short read.

Setup:

- conda create -n pyega3_stable python=3.6
- conda activate pyega3_stable
- pip install pyega3==5.2.0

Replace data_file.py in the libs folder.
