### ISSUE TITLE
-p persistent option, failed chunking slice files, overwrites

### ISSUE THREAD

**Issue by j4jes** [EGA-archive/ega-download-client#36]
Would it be possible to add a -p persistent option to automatically resume dropped connection or broken transfers ? The EGA archive gateway has been getting more usage and when I start pyega3 downloads they rarely make it through the entire weekend or even through the night, so I keep them inside screen sessions and monitor them remotely.

I think pyega should have a -p where it has no prompts, and continuously retries until the file is complete (until slice files make it past concatenation and md5 errors). Without the -p option pyega should have prompts like "md5 integrity failed / slice files did not assemble, start over download?"  Downloads have rarely made it to 100% and survived putting the slice files together lately.

Ive been downloading with -c 4 and found that sometimes it does not resume downloading, and will give md5 does not match, then start back at 0%. This was the case for me here after it had reached 99% then got stuck while trying to concatenate the slice files:

[2019-03-25 09:21:14 -0400] MD5 does NOT match - corrupted download
[2019-03-25 09:21:19 -0400] retry attempt 1
[2019-03-25 09:21:19 -0400] Download starting [using 4 connection(s)]...
0%| | 0.00/156G [00:00<?, ?B/s][2019-03-25 09:21:19 -0400] Request URL : https://ega.ebi.ac.uk:8051/elixir/data/files/EGAF00001835279?destinationFormat=plain

This last week has been hell trying to download from EGA. I've downloaded this file four times now, and it always disappears when I reach 100%, then I must start over. I'm going to try again without -c chunking and see how that goes, but my download time will be increased ten fold.

[jesse@corpus uk_biobank]$ pyega3 -d -c 20 -cf CREDENTIALS_FILE fetch EGAF00001835283
...
[2019-03-29 02:44:49 -0400] Response headers: {'X-Application-Context': 'zuulserver:8051', 'WWW-Authenticate': 'Bearer realm="oauth2-resource", error="invalid_token", error_description="Invalid token: eyJraWQiOiJyc2ExIiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJzaGFudGFsYS5oYXJpZGFzc0BtYWlsLm1jZ2lsbC5jYSIsImF6cCI6ImYyMGNkMmQzLTY4MmEtNDU2OC1hNTNlLTQyNjJlZjU0YzhmNCIsImlzcyI6Imh0dHBzOlwvXC9lZ2EuZWJpLmFjLnVrOjg0NDNcL2VnYS1vcGVuaWQtY29ubmVjdC1zZXJ2ZXJcLyIsImV4cCI6MTU1MzgzMDY2NCwiaWF0IjoxNTUzODI3MDY0LCJqdGkiOiI3OTZjNWYyNC0wZTA0LTQ2YmItODdjYi1kNTczNDAwM2VjNDQifQ.lN9vIrO-PuAaMVJ88xKenEmw6HpwyxiTJ2ygw58UIGnRcqTXd-gVlvTyAvH1EYweaBPesSrQE8yGxe6oo68SQaE2y0G-GmbDth99sxBIrGiY3uwzKVw7JXfN3pbm-DEsKL_zM14yBMPdZ4QWP7-nXemU9dzSpuMAdcIN2k0p7MU"', 'Date': 'Fri, 29 Mar 2019 06:44:48 GMT', 'Content-Type': 'application/json;charset=UTF-8', 'Transfer-Encoding': 'chunked'}
[2019-03-29 02:44:49 -0400] https://ega.ebi.ac.uk:8051 "GET /elixir/data/files/EGAF00001835283?destinationFormat=plain HTTP/1.1" 401 None
[2019-03-29 02:44:49 -0400] Request URL : https://ega.ebi.ac.uk:8051/elixir/data/files/EGAF00001835283?destinationFormat=plain
[2019-03-29 02:44:49 -0400] Response headers: {'X-Application-Context': 'zuulserver:8051', 'WWW-Authenticate': 'Bearer realm="oauth2-resource", error="invalid_token", error_description="Invalid token: eyJraWQiOiJyc2ExIiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJzaGFudGFsYS5oYXJpZGFzc0BtYWlsLm1jZ2lsbC5jYSIsImF6cCI6ImYyMGNkMmQzLTY4MmEtNDU2OC1hNTNlLTQyNjJlZjU0YzhmNCIsImlzcyI6Imh0dHBzOlwvXC9lZ2EuZWJpLmFjLnVrOjg0NDNcL2VnYS1vcGVuaWQtY29ubmVjdC1zZXJ2ZXJcLyIsImV4cCI6MTU1MzgzMDY2NCwiaWF0IjoxNTUzODI3MDY0LCJqdGkiOiI3OTZjNWYyNC0wZTA0LTQ2YmItODdjYi1kNTczNDAwM2VjNDQifQ.lN9vIrO-PuAaMVJ88xKenEmw6HpwyxiTJ2ygw58UIGnRcqTXd-gVlvTyAvH1EYweaBPesSrQE8yGxe6oo68SQaE2y0G-GmbDth99sxBIrGiY3uwzKVw7JXfN3pbm-DEsKL_zM14yBMPdZ4QWP7-nXemU9dzSpuMAdcIN2k0p7MU"', 'Date': 'Fri, 29 Mar 2019 06:44:48 GMT', 'Content-Type': 'application/json;charset=UTF-8', 'Transfer-Encoding': 'chunked'}
[2019-03-29 02:44:49 -0400] https://ega.ebi.ac.uk:8051 "GET /elixir/data/files/EGAF00001835283?destinationFormat=plain HTTP/1.1" 401 None
[2019-03-29 02:44:49 -0400] Request URL : https://ega.ebi.ac.uk:8051/elixir/data/files/EGAF00001835283?destinationFormat=plain
[2019-03-29 02:44:49 -0400] Response headers: {'X-Application-Context': 'zuulserver:8051', 'WWW-Authenticate': 'Bearer realm="oauth2-resource", error="invalid_token", error_description="Invalid token: eyJraWQiOiJyc2ExIiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJzaGFudGFsYS5oYXJpZGFzc0BtYWlsLm1jZ2lsbC5jYSIsImF6cCI6ImYyMGNkMmQzLTY4MmEtNDU2OC1hNTNlLTQyNjJlZjU0YzhmNCIsImlzcyI6Imh0dHBzOlwvXC9lZ2EuZWJpLmFjLnVrOjg0NDNcL2VnYS1vcGVuaWQtY29ubmVjdC1zZXJ2ZXJcLyIsImV4cCI6MTU1MzgzMDY2NCwiaWF0IjoxNTUzODI3MDY0LCJqdGkiOiI3OTZjNWYyNC0wZTA0LTQ2YmItODdjYi1kNTczNDAwM2VjNDQifQ.lN9vIrO-PuAaMVJ88xKenEmw6HpwyxiTJ2ygw58UIGnRcqTXd-gVlvTyAvH1EYweaBPesSrQE8yGxe6oo68SQaE2y0G-GmbDth99sxBIrGiY3uwzKVw7JXfN3pbm-DEsKL_zM14yBMPdZ4QWP7-nXemU9dzSpuMAdcIN2k0p7MU"', 'Date': 'Fri, 29 Mar 2019 06:44:48 GMT', 'Content-Type': 'application/json;charset=UTF-8', 'Transfer-Encoding': 'chunked'}

[2019-03-29 02:44:49 -0400] 401 Client Error: for url: https://ega.ebi.ac.uk:8051/elixir/data/files/EGAF00001835283?destinationFormat=plain
Traceback (most recent call last):
File "/home/jesse/.local/bin/pyega3", line 11, in 
load_entry_point('pyega3==3.0.27', 'console_scripts', 'pyega3')()
File "/home/jesse/.local/lib/python3.6/site-packages/pyega3/pyega3.py", line 433, in main
download_file_retry( token, args.identifier, file_name, file_size, check_sum, args.connections, key, args.saveto, genomic_range_args )
File "/home/jesse/.local/lib/python3.6/site-packages/pyega3/pyega3.py", line 333, in download_file_retry
raise e
File "/home/jesse/.local/lib/python3.6/site-packages/pyega3/pyega3.py", line 328, in download_file_retry
download_file(token, file_id, file_size, check_sum, num_connections, key, output_file)
File "/home/jesse/.local/lib/python3.6/site-packages/pyega3/pyega3.py", line 279, in download_file
for part_file_name in executor.map(download_file_slice_ ,params):
File "/usr/lib64/python3.6/concurrent/futures/_base.py", line 586, in result_iterator
yield fs.pop().result()
File "/usr/lib64/python3.6/concurrent/futures/_base.py", line 432, in result
return self.__get_result()
File "/usr/lib64/python3.6/concurrent/futures/_base.py", line 384, in __get_result
raise self.exception
File "/usr/lib64/python3.6/concurrent/futures/thread.py", line 56, in run
result = self.fn(*self.args, **self.kwargs)
File "/home/jesse/.local/lib/python3.6/site-packages/pyega3/pyega3.py", line 193, in download_file_slice
return download_file_slice(*args)
File "/home/jesse/.local/lib/python3.6/site-packages/pyega3/pyega3.py", line 183, in download_file_slice
r.raise_for_status()
File "/home/jesse/.local/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: for url: https://ega.ebi.ac.uk:8051/elixir/data/files/EGAF00001835283?destinationFormat=plain

After this, the slice files are gone !

[jesse@corpus uk_biobank]$ cd EGAF00001835283/
[jesse@corpus EGAF00001835283]$ ls
[jesse@corpus EGAF00001835283]$ ls -al
total 0
drwxrwxr-x 1 jesse jesse 0 Mar 29 02:43 .
drwxrwxr-x 1 jesse jesse 158 Mar 28 00:07 ..
[jesse@corpus EGAF00001835283]$

**Comment by moldach** [comment]
I second this feature!

**Comment by rjovelin** [comment]
I have the same type of issues reported above.
I haven't been able to download a single file with pyega3.

At present 31 / 71 downloads have stopped at various % of complete download with the error below (40 remains active). The only file that made it to 100% was then removed because md5 doesn't match.

Traceback (most recent call last): 
  File "/u/rjovelin/SOFT/anaconda3/bin/pyega3", line 11, in <module> 
    sys.exit(main()) 
  File "/u/rjovelin/SOFT/anaconda3/lib/python3.6/site-packages/pyega3/pyega3.py", line 365, in main 
    download_file_retry( token, args.identifier, file_name, file_size, check_sum, args.connections, key, args.saveto ) 
  File "/u/rjovelin/SOFT/anaconda3/lib/python3.6/site-packages/pyega3/pyega3.py", line 291, in download_file_retry 
    raise e 
  File "/u/rjovelin/SOFT/anaconda3/lib/python3.6/site-packages/pyega3/pyega3.py", line 286, in download_file_retry 
    download_file( token, file_id, file_name, file_size, check_sum, num_connections, key, output_file) 
  File "/u/rjovelin/SOFT/anaconda3/lib/python3.6/site-packages/pyega3/pyega3.py", line 261, in download_file 
    for part_file_name in executor.map(download_file_slice_ ,params): 
  File "/u/rjovelin/SOFT/anaconda3/lib/python3.6/concurrent/futures/_base.py", line 586, in result_iterator 
    yield fs.pop().result() 
  File "/u/rjovelin/SOFT/anaconda3/lib/python3.6/concurrent/futures/_base.py", line 432, in result 
    return self.__get_result() 
  File "/u/rjovelin/SOFT/anaconda3/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result 
    raise self._exception 
  File "/u/rjovelin/SOFT/anaconda3/lib/python3.6/concurrent/futures/thread.py", line 56, in run 
    result = self.fn(*self.args, **self.kwargs) 
  File "/u/rjovelin/SOFT/anaconda3/lib/python3.6/site-packages/pyega3/pyega3.py", line 187, in download_file_slice_ 
    return download_file_slice(*args) 
  File "/u/rjovelin/SOFT/anaconda3/lib/python3.6/site-packages/pyega3/pyega3.py", line 177, in download_file_slice 
    r.raise_for_status() 
  File "/u/rjovelin/SOFT/anaconda3/lib/python3.6/site-packages/requests/models.py", line 935, in raise_for_status 
    raise HTTPError(http_error_msg, response=self) 
requests.exceptions.HTTPError: 401 Client Error: for url: https://ega.ebi.ac.uk:8051/elixir/data/files/EGAF00001337207?destinationFormat=plain

**Comment by AlexanderVi** [comment]
> I have the same type of issues reported above.
> I haven't been able to download a single file with pyega

Please indicate version your are using

**Comment by AlexanderVi** [comment]
in 990954e ( ver 3.0.33 ) a new command line args have been added ( --max-retries and --retry-wait ). By specifying any negative number as  --max-retries one can achieve the mentioned above "persistent option" (to automatically resume dropped connection or broken transfers indefinitely until the file is successfully downloaded ). E.g. 

    pyega3 -cf ega.json fetch EGAD00000000001 --max-retries=-1

**Comment by j4jes** [comment]
Thanks. 

To answer your question, I was using the pyega version from a pip3 install on centos7 (v3.0.30)

**Comment by AlexanderVi** [comment]
> To answer your question, I was using the pyega version from a pip3 install on centos7 (v3.0.30)

Good to know. 401 error ( token expired ) has been fixed in 3.0.31

**Comment by rjovelin** [comment]
I am using pyega3 version 3.0.21 installed from conda

**Comment by AlexanderVi** [comment]
> I am using pyega3 version 3.0.21 installed from conda

I suggest everyone to upgrade to 3.0.33 via pip now ( on conda it will be available later due to the fact that the recipe needs approval from the bioconda channel admins )
