### ISSUE TITLE
requests.exceptions.HTTPError: 500 Server Error:  for url:

### ISSUE THREAD

**Issue by biocoreexpert** [EGA-archive/ega-download-client#39]
yEGA3 - EGA python client version 3.0.33 (https://github.com/EGA-archive/ega-download-client)
Parts of this software are derived from pyEGA (https://github.com/blachlylab/pyega) by James Blachly

[2019-05-06 20:43:19 +0200] Authentication success for user 'xxxxxx@ntnu.no'
Traceback (most recent call last):
  I am getting this error trying to download data:

File "/local/home/robinm/software2/ega-download-client/pyega3/pyega3.py", line 474, in <module>
    main()
  File "/local/home/robinm/software2/ega-download-client/pyega3/pyega3.py", line 467, in main
    file_name, file_size, check_sum = get_file_name_size_md5( token, args.identifier )            
  File "/local/home/robinm/software2/ega-download-client/pyega3/pyega3.py", line 147, in get_file_name_size_md5
    r.raise_for_status()
  File "/local/home/robinm/miniconda2/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error:  for url: https://ega.ebi.ac.uk:8051/elixir/data/metadata/files/EGAF000

**Comment by AlexanderVi** [comment]
Please contact EGA helpdesk at **helpdesk@ega-archive.org** regarding internal server errors (500 Server Error) as they are not related to the EGA python client (pyEga3)
