### ISSUE TITLE
Connection Aborted 

### ISSUE THREAD

**Issue by mchburch** [EGA-archive/ega-download-client#48]
I am running into a 'Connection Aborted' error when trying to download datasets. The smaller files seem to download fine but when it gets to larger files this error eventually comes about and then kills the entire job. I have a PBS job to try to install many datasets because I know it will take some time but when this error comes about I have to retry without any knowledge of which files successfully downloaded completely. I am not sure if this is due to an installation error on my part or a possible server issue.  I also see the system re-authenticating to try and recover and continue the download which works sometimes but not always.

I have installed 'pyega3' using the following:  python3 -m pip install pyega3 
The version that is installed is the following: pyega3 (3.0.38)
The command that I am attempting to use is the following: 
python3 /home/mcburch/.local/lib/python3.6/site-packages/pyega3/pyega3.py -cf ega_credentials.json fetch EGAD00000000001

Then I get the following trace: 
`Traceback (most recent call last):
  File "/home/mcburch/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 603, in urlopen
    chunked=chunked)
  File "/home/mcburch/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/mcburch/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib64/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/usr/lib64/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib64/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib64/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib64/python3.6/ssl.py", line 1012, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib64/python3.6/ssl.py", line 874, in read
    return self._sslobj.read(len, buffer)
  File "/usr/lib64/python3.6/ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mcburch/.local/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/mcburch/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 641, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/mcburch/.local/lib/python3.6/site-packages/urllib3/util/retry.py", line 368, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/mcburch/.local/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/mcburch/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 603, in urlopen
    chunked=chunked)
  File "/home/mcburch/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/mcburch/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib64/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/usr/lib64/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib64/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib64/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib64/python3.6/ssl.py", line 1012, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib64/python3.6/ssl.py", line 874, in read
    return self._sslobj.read(len, buffer)
  File "/usr/lib64/python3.6/ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mcburch/.local/lib/python3.6/site-packages/pyega3/pyega3.py", line 488, in <module>
    main()
  File "/home/mcburch/.local/lib/python3.6/site-packages/pyega3/pyega3.py", line 478, in main
    download_dataset( credentials, args.identifier, args.connections, key, args.saveto, genomic_range_args, args.max_retries, args.retry_wait )
  File "/home/mcburch/.local/lib/python3.6/site-packages/pyega3/pyega3.py", line 378, in download_dataset
    if( not dataset_id in api_list_authorized_datasets(token) ):
  File "/home/mcburch/.local/lib/python3.6/site-packages/pyega3/pyega3.py", line 82, in api_list_authorized_datasets
    r = requests.get(url, headers=headers)
  File "/home/mcburch/.local/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/mcburch/.local/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/mcburch/.local/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/mcburch/.local/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/mcburch/.local/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))`

This did not seem to relate to previous issues but any help is appreciated!

**Comment by AlexanderVi** [comment]
This is related to a problem on the server side ( usually 104 ConnectionResetError happens after "slice error" ). The workaround is to increase the retry_wait to 30 or 60 seconds (add **--retry-wait 60** to the command line ). This give the server time to recover.

**Comment by mchburch** [comment]
After adding those to my commands I get the following error:

Parts of this software are derived from pyEGA (https://github.com/blachlylab/pyega) by James Blachly
usage: pyega3.py [-h] [-d] -cf CREDENTIALS_FILE [-c CONNECTIONS]
                 {datasets,files,fetch} ...
pyega3.py: error: argument subcommand: invalid choice: '60' (choose from 'datasets', 'files', 'fetch')

Do I not have the correct version of pyega3 installed or is there a way to enable those optional arguments? Let me know when you can!

Thank you

**Comment by AlexanderVi** [comment]
append **--retry-wait 60** to the end of command line ( or upgrade to v.3.0.39 where 60s is default delay )
