### ISSUE TITLE
HTTPError: 500

### ISSUE THREAD

**Issue by hotellive123** [EGA-archive/ega-download-client#52]
I get the HTTPError 500 when I try to view my datasets. It shows authentication success.  I contract the EGA helpdesk, but he can't resolve this. I also try to install python3 and pyega3 in different computers and systems (win7, win10, centos), but  fail again. Is this related to the database server issue?

pyEGA3 - EGA python client version 3.0.39 (https://github.com/EGA-archive/ega-download-client)
Parts of this software are derived from pyEGA (https://github.com/blachlylab/pyega) by James Blachly
[debugging]

Server URL: https://ega.ebi.ac.uk:8051/elixir/data
Session-Id: 3914652913
[2019-09-18 17:06:26 +0800] Starting new HTTPS connection (1): ega.ebi.ac.uk:8443
[2019-09-18 17:07:54 +0800] https://ega.ebi.ac.uk:8443 "POST /ega-openid-connect-server/token HTTP/1.1" 200 None
[2019-09-18 17:07:54 +0800] <Response [200]>

[2019-09-18 17:07:54 +0800] Request URL : https://ega.ebi.ac.uk:8443/ega-openid-connect-server/token
[2019-09-18 17:07:54 +0800] Response    :
 {
    "access_token": "xxxxxxxxxxxxxx",
    "token_type": "Bearer",
    "expires_in": 3584,
    "scope": "openid"
}
[2019-09-18 17:07:54 +0800] Authentication success for user 'xxxxx@xxxx.com'
[2019-09-18 17:07:54 +0800] Starting new HTTPS connection (1): ega.ebi.ac.uk:8051
[2019-09-18 17:08:54 +0800] https://ega.ebi.ac.uk:8051 "GET /elixir/data/metadata/datasets HTTP/1.1" 500 None
Traceback (most recent call last):
  File "pyega3.py", line 494, in <module>
    main()
  File "pyega3.py", line 471, in main
    reply = api_list_authorized_datasets(token)
  File "pyega3.py", line 88, in api_list_authorized_datasets
    r.raise_for_status()
  File "/usr/local/python3.7/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error:  for url: https://ega.ebi.ac.uk:8051/elixir/data/metadata/datasets

**Comment by anandmohan777** [comment]
Hi hotellive123, extremely sorry for the late response. Are you still getting the error?

**Comment by anandmohan777** [comment]
We have upgraded our servers so pls update the pyega3 using command 'pip3 install update pyega3 -U' and then try the download.

**Comment by chiara111p111** [comment]
Hi, I'm having the same error. @brucemoran have you resolved it somehow?

**Comment by JMencius** [comment]
Error persists in 2025. 11. 21

**Comment by skywalker51616** [comment]
Error is dataset-specific. I can download one dataset, but not the other using the same command: 
pyega3 -c 50 -cf credential_file.json fetch --reference-name 21 --output-dir $EGA_ID/ $EGA_ID

Error message:
[2025-11-26 17:42:07 +0800] Error: '500 Server Error:  for url: https://ega.ebi.ac.uk:8443/v2/htsget/reads/EGAF00001131840?referenceName=21&format=CRAM' occured; sleeping 60s before retrying (attempt=1)
