### ISSUE TITLE
Time out error

### ISSUE THREAD

**Issue by anoyaro84** [EGA-archive/ega-download-client#6]
I was able to log-in but it appears to be not possible to make a connection.
Could you help me to progress further?

Please find the messages I got below:

python ega-download-client/pyega3.py -cf credential.json files EGAD00001003461 
EGA python client version 3.0.0
Authentication success for user 's.stelloo@nki.nl'
Traceback (most recent call last):
  File "/home/yo.kim/miniconda3/envs/EGA/lib/python3.6/site-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/home/yo.kim/miniconda3/envs/EGA/lib/python3.6/site-packages/urllib3/util/connection.py", line 83, in create_connection
    raise err
  File "/home/yo.kim/miniconda3/envs/EGA/lib/python3.6/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yo.kim/miniconda3/envs/EGA/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/home/yo.kim/miniconda3/envs/EGA/lib/python3.6/site-packages/urllib3/connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "/home/yo.kim/miniconda3/envs/EGA/lib/python3.6/site-packages/urllib3/connectionpool.py", line 850, in _validate_conn
    conn.connect()
  File "/home/yo.kim/miniconda3/envs/EGA/lib/python3.6/site-packages/urllib3/connection.py", line 284, in connect
    conn = self._new_conn()
  File "/home/yo.kim/miniconda3/envs/EGA/lib/python3.6/site-packages/urllib3/connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7f6c926d07b8>: Failed to establish a new connection: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yo.kim/miniconda3/envs/EGA/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/home/yo.kim/miniconda3/envs/EGA/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/yo.kim/miniconda3/envs/EGA/lib/python3.6/site-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='ega.ebi.ac.uk', port=8051): Max retries exceeded with url: /elixir/data/metadata/datasets (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f6c926d07b8>: Failed to establish a new connection: [Errno 110] Connection timed out',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "ega-download-client/pyega3.py", line 352, in <module>
    main()
  File "ega-download-client/pyega3.py", line 338, in main
    reply = api_list_files_in_dataset(token, args.identifier)
  File "ega-download-client/pyega3.py", line 84, in api_list_files_in_dataset
    if( not dataset in api_list_authorized_datasets(token) ):
  File "ega-download-client/pyega3.py", line 63, in api_list_authorized_datasets
    r = requests.get(url, headers = headers)
  File "/home/yo.kim/miniconda3/envs/EGA/lib/python3.6/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/home/yo.kim/miniconda3/envs/EGA/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/yo.kim/miniconda3/envs/EGA/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/yo.kim/miniconda3/envs/EGA/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/yo.kim/miniconda3/envs/EGA/lib/python3.6/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='ega.ebi.ac.uk', port=8051): Max retries exceeded with url: /elixir/data/metadata/datasets (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f6c926d07b8>: Failed to establish a new connection: [Errno 110] Connection timed out',))

**Comment by eatsai** [comment]
I'm also having the same issue. Does anyone know how to resolve this?

Thanks,
Ellen

**Comment by eatsai** [comment]
It seems a couple ports need to be open for this script to run: The ports for the python client should be HTTPS 8051 and for authentication HTTPS 8443. I was able to run the script successfully now.

The help desk kindly sent me this small test script:
import requests
r = requests.get("https://ega.ebi.ac.uk:8051/elixir/central/stats/load")
print(r)

**Comment by AlexanderSenf** [comment]
Thank you - I have added this as a requirement to the README file.

**Comment by shokohirosue** [comment]
Hello, the server seems to be down again. Could you look into this? Thanks!

**Comment by AlexanderVi** [comment]
The server has been restarted - should be fine now.

**Comment by biocoreexpert** [comment]
is the server down? having the same issue today

**Comment by wahbi** [comment]
hello everyone i'm using the egadownloadclient V2 , the one that was built with java , i followed the instructions provided here : 
 https://github.com/elixir-europe/human-data-local-ega

and tried to run the client with this command : 
java -jar /home/ega/EGA_local/public/download/EgaDemoClient.jar -local 172.17.0.4:8111 172.17.0.4:8112

then test the bandwidth within the client shell : testbandwidth 

it never succeed :  
 EGA > testbandwidth
Requesting....
Server error. Refreshing Session!
Requesting....


so i checked the monit logfile and i found this : 

[UTC Sep 13 11:08:37] error    : 'localhost_res9124' failed protocol test [HTTP] at [localhost]:9124/ega/rest/res/v1/stats/load [TCP/IP] -- Cannot assign requested address


can you help with this please ?  appreciate it

**Comment by AlexanderVi** [comment]
with questions related to egadownloadclient V2 (the one that was built with java) please contact EGA helpdesk
