### ISSUE TITLE
download a specific genome region

### ISSUE THREAD

**Issue by jml96** [EGA-archive/ega-download-client#65]
Hi,
I am using pyega3 to fetch bam files from study EGAS00001003611.
When I use this command
./pyega3 -c 10 -cf ./ega_credential_file.json fetch EGAF00002727296 --reference-name chr17 --start 1 --end 81195210

I get the following error.

Traceback (most recent call last):
  File "./pyega3/lib/python3.8/site-packages/htsget/io.py", line 94, in __get
    response.raise_for_status()
  File "./pyega3/lib/python3.8/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error:  for url: https://ega.ebi.ac.uk:8052/elixir/tickets/tickets/files/EGAF00002727296?referenceName=chr17&start=1&end=81195210

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./pyega3/bin/pyega3", line 10, in <module>
    sys.exit(main())
  File "./pyega3/lib/python3.8/site-packages/pyega3/pyega3.py", line 546, in main
    download_file_retry( credentials, args.identifier, file_name, file_size, check_sum, args.connections, key, args.saveto, genomic_range_args, args.max_retries, args.retry_wait )
  File "./pyega3/lib/python3.8/site-packages/pyega3/pyega3.py", line 388, in download_file_retry
    htsget.get(
  File "./pyega3/lib/python3.8/site-packages/htsget/io.py", line 80, in get
    manager.run()
  File "./pyega3/lib/python3.8/site-packages/htsget/protocol.py", line 140, in run
    self.__retry(self._handle_ticket_request)
  File "./pyega3/lib/python3.8/site-packages/htsget/protocol.py", line 111, in __retry
    method(*args)
  File "./pyega3/lib/python3.8/site-packages/htsget/io.py", line 138, in _handle_ticket_request
    first_piece = next(stream, "").decode(encoding)
  File "./pyega3/lib/python3.8/site-packages/htsget/io.py", line 105, in _stream
    response = self.__get(url, headers=headers, stream=True, timeout=self.timeout)
  File "./pyega3/lib/python3.8/site-packages/htsget/io.py", line 98, in __get
    raise exceptions.ClientError(str(he), response.text)
htsget.exceptions.ClientError: 404 Client Error:  for url: https://ega.ebi.ac.uk:8052/elixir/tickets/tickets/files/EGAF00002727296?referenceName=chr17&start=1&end=81195210:{"timestamp":1580744442267,"status":404,"error":"Not Found","exception":"eu.elixir.ega.ebi.htsget.config.IndexNotFoundException","message":"IndexFileId not found for file: EGAF00002727296","path":"/tickets/files/EGAF00002727296"}

It seems that the index files are missing and for this reason htsget is unable to fetch specific regions in the bam file. Could you please confirm this to me or help me with a solution to resolve this issue?
I have no issue fetching all bam file.
Thank you in advance.

Regards,
João

**Comment by hubentu** [comment]
Hi @jml96 @malloryfreeberg ,

I got the same error when trying to download BAM in a genomic region from EGAD00001001039. Could you please help me to check this issue? Is this caused by missing index files or is this feature not supported anymore?
btw. is there a feature to download a subset of BAM with a bed file?

Thanks,
Qiang
