### ISSUE TITLE
501 Server Error

### ISSUE THREAD

**Issue by vb-ak** [EGA-archive/ega-download-client#86]
Hello, 

I'm trying to download a file using the command

```pyega3 -cf credentials.json fetch EGAF00000XXXXXX ```

User authorization seems to be successful and it seems to recognize the correct file (X'ed out here), but then there's a 501 server error and it breaks off after 5 retries. Appreciate any thoughts on what might be going wrong. Thanks!

```[2020-07-15 16:41:04 +0000] Authentication success for user 'XXXX@YYYY'
[2020-07-15 16:41:04 +0000] File Id: 'EGAF00000XXXXXX'(4359732774 bytes).
[2020-07-15 16:41:04 +0000] Download starting [using 1 connection(s)]...
^M  0%|          | 0.00/4.36G [00:00<?, ?B/s]^M  0%|          | 0.00/4.36G [00:06<?, ?B/s]
[2020-07-15 16:41:11 +0000] 501 Server Error:  for url: https://ega.ebi.ac.uk:8052/elixir/data/files/EGAF00000XXXXXX?destinationFormat=plain
[2020-07-15 16:42:11 +0000] retry attempt 1
[2020-07-15 16:42:11 +0000] Download starting [using 1 connection(s)]...
^M  0%|          | 0.00/4.36G [00:00<?, ?B/s]^M  0%|          | 0.00/4.36G [00:06<?, ?B/s]
[2020-07-15 16:42:17 +0000] 501 Server Error:  for url: https://ega.ebi.ac.uk:8052/elixir/data/files/EGAF00000XXXXXX?destinationFormat=plain
[2020-07-15 16:43:17 +0000] retry attempt 2
[2020-07-15 16:43:17 +0000] Download starting [using 1 connection(s)]...
^M  0%|          | 0.00/4.36G [00:00<?, ?B/s]^M  0%|          | 0.00/4.36G [00:00<?, ?B/s]
[2020-07-15 16:43:18 +0000] 501 Server Error:  for url: https://ega.ebi.ac.uk:8052/elixir/data/files/EGAF00000XXXXXX?destinationFormat=plain
[2020-07-15 16:44:18 +0000] retry attempt 3
[2020-07-15 16:44:18 +0000] Download starting [using 1 connection(s)]...
^M  0%|          | 0.00/4.36G [00:00<?, ?B/s]^M  0%|          | 0.00/4.36G [00:06<?, ?B/s]
[2020-07-15 16:44:24 +0000] 501 Server Error:  for url: https://ega.ebi.ac.uk:8052/elixir/data/files/EGAF00000XXXXXX?destinationFormat=plain
[2020-07-15 16:45:24 +0000] retry attempt 4
[2020-07-15 16:45:24 +0000] Download starting [using 1 connection(s)]...
^M  0%|          | 0.00/4.36G [00:00<?, ?B/s]^M  0%|          | 0.00/4.36G [00:00<?, ?B/s]
[2020-07-15 16:45:24 +0000] 501 Server Error:  for url: https://ega.ebi.ac.uk:8052/elixir/data/files/EGAF00000XXXXXX?destinationFormat=plain
[2020-07-15 16:46:25 +0000] retry attempt 5
[2020-07-15 16:46:25 +0000] Download starting [using 1 connection(s)]...
^M  0%|          | 0.00/4.36G [00:00<?, ?B/s]^M  0%|          | 0.00/4.36G [00:00<?, ?B/s]
[2020-07-15 16:46:25 +0000] 501 Server Error:  for url: https://ega.ebi.ac.uk:8052/elixir/data/files/EGAF00000XXXXXX?destinationFormat=plain
Traceback (most recent call last):
  File "/usr/local/bin/pyega3", line 11, in <module>
    load_entry_point('pyega3==3.1.0', 'console_scripts', 'pyega3')()
  File "/usr/local/lib/python3.7/site-packages/pyega3/pyega3.py", line 613, in main
    args.saveto, genomic_range_args, args.max_retries, args.retry_wait)
  File "/usr/local/lib/python3.7/site-packages/pyega3/pyega3.py", line 467, in download_file_retry
    raise e
  File "/usr/local/lib/python3.7/site-packages/pyega3/pyega3.py", line 462, in download_file_retry
    download_file(token, file_id, file_size, check_sum, num_connections, key, output_file)
  File "/usr/local/lib/python3.7/site-packages/pyega3/pyega3.py", line 395, in download_file
    for part_file_name in executor.map(download_file_slice_, params):
  File "/usr/lib64/python3.7/concurrent/futures/_base.py", line 598, in result_iterator
    yield fs.pop().result()
  File "/usr/lib64/python3.7/concurrent/futures/_base.py", line 435, in result
    return self.__get_result()
  File "/usr/lib64/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/lib64/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/site-packages/pyega3/pyega3.py", line 269, in download_file_slice_
    return download_file_slice(*args)
  File "/usr/local/lib/python3.7/site-packages/pyega3/pyega3.py", line 255, in download_file_slice
    r.raise_for_status()
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 501 Server Error:  for url: https://ega.ebi.ac.uk:8052/elixir/data/files/EGAF00000XXXXXX?destinationFormat=plain
```

**Comment by malloryfreeberg** [comment]
Hi @vb-ak . Thank you for reporting this issue. As this is an issue related to your specific account, if you are still experiencing this behaviour please run your command using the `-d` debug flag - which will generate a log - and email the log to the EGA Helpdesk at helpdesk@ega-archive.org for further assistance. Thank you!
