### ISSUE TITLE
requests.exceptions.HTTPError: 500 Server Error

### ISSUE THREAD

**Issue by jianguozhouzunyimedicaluniversity** [EGA-archive/ega-download-client#96]
Could you please help me to check this error, however, other datasets is worked.
Best,
````
(ega) [rstudio@Zhou-EU-1 EGAD00001000221]$ pyega3  -c 20 -cf ~/hdd/EGA/zjg.zmu_credential_file.json fetch EGAF00000128154
pyEGA3 - EGA python client version 3.1.0 (https://github.com/EGA-archive/ega-download-client)
Parts of this software are derived from pyEGA (https://github.com/blachlylab/pyega) by James Blachly

Server URL: https://ega.ebi.ac.uk:8052/elixir/data
Session-Id: 2255474265

[2020-10-14 00:15:02 +0000] Authentication success for user '********'
Traceback (most recent call last):
  File "/home/rstudio/miniconda2/envs/ega/bin/pyega3", line 10, in <module>
    sys.exit(main())
  File "/home/rstudio/miniconda2/envs/ega/lib/python3.6/site-packages/pyega3/pyega3.py", line 611, in main
    file_name, file_size, check_sum = get_file_name_size_md5(token, args.identifier)
  File "/home/rstudio/miniconda2/envs/ega/lib/python3.6/site-packages/pyega3/pyega3.py", line 222, in get_file_name_size_md5
    r.raise_for_status()
  File "/home/rstudio/miniconda2/envs/ega/lib/python3.6/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error:  for url: https://ega.ebi.ac.uk:8052/elixir/data/metadata/files/EGAF00000128154
````

**Comment by malloryfreeberg** [comment]
Hi @jianguozhouzunyimedicaluniversity,

Thank you for reporting this issue. As this is a service issue, if you are still experiencing this behaviour, please email the EGA Helpdesk at helpdesk@ega-archive.org for further assistance.
