### ISSUE TITLE
error 500 

### ISSUE THREAD

**Issue by AminaJbara** [EGA-archive/ega-download-client#99]
Hello,

I hope that someone here can help me with Error 500, I contact the EGAhelp desk and I didn't get any response.

Thank you,
Amina
 

pyEGA3 - EGA python client version 3.4.0 (https://github.com/EGA-archive/ega-download-client)
 Parts of this software are derived from pyEGA (https://github.com/blachlylab/pyega) by James Blachly
Python version : 3.9.0
 OS version : Linux #1 SMP Tue Aug 13 16:21:39 IDT 2019
Server URL: https://ega.ebi.ac.uk:8052/elixir/data
 Session-Id: 2491714505
Authentication success for user '**********'
Traceback (most recent call last):
  File "/usr/local/bioinfo/bioconda/envs/pyega3/bin/pyega3", line 10, in <module>
    sys.exit(main())
  File "/usr/local/bioinfo/bioconda/envs/pyega3/lib/python3.9/site-packages/pyega3/pyega3.py", line 666, in main
    download_dataset(credentials, args.identifier, args.connections, key, args.saveto, genomic_range_args,
  File "/usr/local/bioinfo/bioconda/envs/pyega3/lib/python3.9/site-packages/pyega3/pyega3.py", line 516, in download_dataset
    if (not dataset_id in api_list_authorized_datasets(token)):
  File "/usr/local/bioinfo/bioconda/envs/pyega3/lib/python3.9/site-packages/pyega3/pyega3.py", line 163, in api_list_authorized_datasets
    r.raise_for_status()
  File "/usr/local/bioinfo/bioconda/envs/pyega3/lib/python3.9/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error:  for url: https://ega.ebi.ac.uk:8052/elixir/data/metadata/datasets

**Comment by danarte** [comment]
Got the same error when trying to download a file.

```
[2020-12-08 17:42:23 +0200] Authentication success for user '*****'
Traceback (most recent call last):
  File "/groups/***/.local/bin//pyega3", line 8, in <module>
    sys.exit(main())
  File "/groups/***/.local/lib/python3.5/site-packages/pyega3/pyega3.py", line 670, in main
    display_file_name, file_name, file_size, check_sum = get_file_name_size_md5(token, args.identifier)
  File "/groups/***/.local/lib/python3.5/site-packages/pyega3/pyega3.py", line 250, in get_file_name_size_md5
    r.raise_for_status()
  File "/share/apps/python/python351/lib/python3.5/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error:  for url: https://ega.ebi.ac.uk:8052/elixir/data/metadata/files/EGAF***
```

**Comment by malloryfreeberg** [comment]
Hi @AminaJbara and @danarte. Thank you for reporting this issue. I can see that pyega3 itself is working for both of you, since it is able to authenticate your accounts successfully. Therefore, since this appears to be a service-related issue, if you are still experiencing this behavior please email EGA Helpdesk at helpdesk@ega-archive.org with this issue and attach the output log produced by pyega3 (pyega3_output.log). The Helpdesk team can then provide further assistance. 

@AminaJbara - Thank you for previously contacting the EGA Helpdesk team. Please continue to correspond with the Helpdesk team through that channel.

Thank you both, and apologies for the inconvenience.
